### ISSUE TITLE
On_best callback function in GeneticAlgorithm

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#111]
GeneticAlgorithm currently uses the local search intensification procedure whenever a new best solution is found.  #98 will implement intensification at each iteration (with some probability) making the current on best implementation somewhat redundant. 

We should implement a more general `on_best` method to the genetic algorithm, similar to how it's done in [ALNS](https://github.com/N-Wouda/ALNS/blob/master/alns/ALNS.py#L226).

**Comment by N-Wouda** [comment]
Before we do this particular callback function, I think we should have a more general idea of what kind of events a user can register custom code for/what we want to support.

**Comment by leonlan** [comment]
From https://github.com/N-Wouda/PyVRP/issues/164#issue-1608261274:

> Now I think it's great if a ready to use GeneticAlgorithm is part of PyVRP, but I don't think it needs to support a lot of customization (like #111 which are hard to get right for every use case), as for those users can just implement their own algorithm inspired by the examples.

I agree with Wouter that we shouldn't support customizations such as `on_best`. Users can simply create their own algorithms if they really want to have it. Unless we find a good reason to have things like `on_best`, I propose to benchmark this feature (with and without `intensify_on_best`) and if there's no meaningful performance difference, then we should just drop it.

**Comment by N-Wouda** [comment]
@leonlan should we close this? I'm not sure. I personally don't feel the need to support this right now, but that might change later when we have an actual use case. Based on the comments above it seems to me that this issue is quite stale, with no work being planned. We might just as well close it if that's the case.

**Comment by leonlan** [comment]
Let's close it. This is an old idea that I don't need or see myself using in the near future.
