### ISSUE TITLE
Individual.cost() incorrect occassionally

### ISSUE THREAD

**Issue by wouterkool** [PyVRP/PyVRP#113]
#### Describe the bug

When running the example VRPTW notebook, sometimes the `individual.cost()` resulting from the first optimization (on instance RC208) is not correct and gives a large value (e.g. `3246399057`). The routes are correct and when initializing a new individual with the same routes and a new penalty manager. Making a copy via the copy constructor the costs are still incorrect, so I suspect this has to do with the fact that the individual has a reference to the penalty manager, which gets deallocated as it goes out of scope after returning from the `solve()` function, but I cannot reproduce this consistently.

In general, should the PenaltyManager be kept alive as long as the solution is alive? This is an undesired situation I think and it would be better to pass PenaltyManager or a penalties object explicitly to the `Individual::cost()` function (see #100).

#### Code sample

See [examples/vrptw.ipynb](https://github.com/N-Wouda/PyVRP/blob/482bf1a71e2bf150b69206eaa3f8a29669a2d8c2/examples/vrptw.ipynb).

```python
# See vrptw.ipynb first run
# args = {"seed": 42, "max_runtime": 10}
# result = solve(instance, **args)
# solution = result.best

routes = solution.get_routes()
route_stats = diagnostics.get_all_route_statistics(solution, instance)

# Make a copy using individual
solution2 = Individual(solution)
route_stats2 = diagnostics.get_all_route_statistics(solution2, instance)

# Make a copy using routes
pm = PenaltyManager(instance.vehicle_capacity)
solution3 = Individual(instance, pm, routes)
route_stats3 = diagnostics.get_all_route_statistics(solution3, instance)

print(solution.has_excess_capacity(), solution.has_time_warp())
print(solution.cost(), sum([s.distance for s in route_stats]))
print(solution2.cost(), sum([s.distance for s in route_stats2]))
print(solution3.cost(), sum([s.distance for s in route_stats3]))
```
gives:
```
False False
3246399057 7761
3246399057 7761
7761 7761
```

This doesn't reproduce the issue and seems to work fine:
```python
# Create individual with penalties trying to reproduce incorrect cost bug
def test():
    pm = PenaltyManager(instance.vehicle_capacity)
    sol = Individual(instance, pm, [[i + 1 for i in range(100)]])
    # Test result inside function
    print(sol.cost())
    return sol

# Test result outside function
sol = test()
print(sol.cost())

# Test after garbage collection
import gc
gc.collect()
print(sol.cost())
```
outputs
```
203004
203004
203004
```

I'm running:
```
INSTALLED VERSIONS
------------------
     pyvrp: 0.0.1
     numpy: 1.24.2
matplotlib: 3.6.3
    Python: 3.10.6
```

#### Expected Output

The individual.cost() function should compute the correct cost regardless of whether the PenaltyManager is still in scope (I think?).

**Comment by N-Wouda** [comment]
Yes, that's exactly what's going on. Related: how do we handle the instance going out of scope? That's also passed by reference.

**Comment by N-Wouda** [comment]
I suspect we need to use [`py::keep_alive`](https://pybind11.readthedocs.io/en/stable/advanced/functions.html#keep-alive) in a few places to prevent this from happening.

**Comment by N-Wouda** [comment]
#135 fixes this by keeping the relevant objects alive while the individual is still in scope.

**Comment by N-Wouda** [comment]
#135 fixed this for the instances I was running, but doesn't seem to have done the trick for the Solomon instances now used in the CI. I do not know why not, but for now I'm reopening this issue.

**Comment by N-Wouda** [comment]
When running the CLI, the problem occurs here:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/16272507/221664128-6793478f-02b7-4789-84cc-7fa6b87b05f3.png">
After returning from `solve()`, all objects there are no longer in scope. When calling `print(res)`, the result object internally calls `self.best.cost()`, which evaluates `Individual::cost()` and that seems not to work correctly.

I am not sure why because Individuals have `py::keep_alive` on both the ProblemData and PenaltyManager objects when they are constructed. Something to investigate.

**Comment by N-Wouda** [comment]
I'm going to spend some time on this tomorrow. I think this is the reason the notebooks sometimes fail, and I want to figure out what's going wrong.

**Comment by N-Wouda** [comment]
I'm pretty sure the CostEvaluator changes fixed this, so I'm closing this (hopefully for good!).
