### ISSUE TITLE
LocalSearch API

### ISSUE THREAD

**Issue by wouterkool** [PyVRP/PyVRP#122]
We should think about how to use the `LocalSearch` object. There are several things for which we should consider if they should:
* be set via constructor (i.e. assuming it will be constant after initializing)
* set via property (i.e. can be changed from time to time)
* or taken as argument in `run`/`search`/`intensify` (assumed to change for every run)

We should consider:
* problem data (constructor / fixed)
* operators (constructor / fixed?)
* neighbourhoods (constructor and/or property, changing occasionally)
* penalty manager (penalties/objective object that changes frequently so argument to `run`)
* individual (argument to `run`, will change frequently)
* parameters (mix, some are fixed, some can change e.g. intensification params)

**Comment by N-Wouda** [comment]
Oh, I think I can put the comment from #121 here:

>Instead of a degree in [0, 360] for `overlapToleranceDegrees` in `LocalSearch::intensify`, I think it makes much more sense to use a percentage [0, 1.0]. We can translate that back to a degree/CircleSector integer internally, but then users don't have to understand that there's a circle sector thing around at all. It's just "how much should routes overlap before we consider them in the intensification routine". How we determine that overlap exactly is more of a detail; to a user, we just present a percentage.

**Comment by N-Wouda** [comment]
Is there anything here that we should still like to change? If not, I propose we close this issue.
