### ISSUE TITLE
High-level interfaces `solve_cvrp` and `solve_vrptw`

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#132]
From https://github.com/N-Wouda/PyVRP/issues/48#issuecomment-1406684143

> I think we should do the following.
> 
> First, we offer two high-level solver routines in the pyvrp package: `solve_cvrp()` and `solver_vrptw()`. These take only the bare minimum of arguments (perhaps only a ProblemData instance) and are intended for users that only want to solve the problem, and do not care at all about _how_. This is intentionally a black box. These routines return a Result object that contains some statistics, and the best solution, and everything else is basically a hidden implementation detail.
> 
> For these functions, we compile two versions of our codebase: one where we use the TWS data, and another where we do not, using compile time flags. The compiler will optimise for each case. In the high-level solver routines, we then use the appropriate binary to implement the solver function.
> 
> For people's own use cases, we expose only the full/complete components, not the faster, problem-specific implementations.

**Comment by N-Wouda** [comment]
Purely realistically, this is something we're going to do after the initial submission. For the immediate future I think the different compilation modes are sufficient.

**Comment by N-Wouda** [comment]
The interface for this can be something like `solve_<variant>(data: ProblemData)`. Together with the high-level interface of #217 it should then be pretty easy to model and solve each variant.

**Comment by N-Wouda** [comment]
We promised this in the paper, but I just tinkered with it a bit and would like not to do this (yet). It's particularly tricky because we have objects that are wrapped in Python - those have hardcoded dependencies on the location of a particular native extension. If we want this, we need to think about a way to do that differently.

For now it's enough for me that we support this via compilation flags.

**Comment by N-Wouda** [comment]
OK, I just checked the paper again, and I don't think we explicitly promise this. We just talk about PyVRP being easy to use. Then I think #217 and the associated PR are enough for now.

**Comment by N-Wouda** [comment]
@leonlan @wouterkool shall we close this?

**Comment by leonlan** [comment]
Sure #236 closes this for me
