### ISSUE TITLE
Various HGS improvements by other EURO-NeurIPS teams

### ISSUE THREAD

**Issue by wouterkool** [PyVRP/PyVRP#181]
While OptiML was the clear winner for the static VRPTW, several other teams made improvements to the static HGS solver for the [EURO Meets NeurIPS 2022](https://euro-neurips-vrp-2022.challenges.ortec.com/) competition. We could see if we could benefit from them (or invite them to contribute to this repo?):

Kleopatra (https://github.com/tumBAIS/euro-meets-neurips-2022 not yet available):
* Persist unchanged routes (`LocalSearch::lastModified`) across local searches as SREX does keep some routes unchanged, checking these again after crossover is useless
* Don't shuffle correlated neighbours as they introduce bad arcs with limited runtimes (I think we do the same in keeping the order fixed, but they are ordered by index rather than proximity, while this team suggests ordering them by proximity yields faster improvement)?
* Reduce iterations until restart because less shuffling causes less randomness in the search

Team SB (https://github.com/yd-kwon/NeurIPS-2022-VRPTW-Competition):
* Generalize binary to k-ary tournament to focus more on higher fitness individuals (this gave most performance improvement)
* Always remove individuals after number of offspring to encourage diversity (small but significant improvement)
* Restart mechanism uses warm start from previous population (rather than completely random)

MTGBWS (https://github.com/steveharenberg/sas-euro-neurips-vrp-2022):
* Corrected problematic bugs, integer overflow, division by zero, looping order-sensitive over unordered set (I assume these have all been fixed here as well?)
* Rewrite recursive calls that were not inlined (5-10% improvement)
* Swap data structures, remove o(n) search by o(1) lookup (not sure what is meant exactly, maybe searching for the first empty route in local search?)
* Matrix in 2D array implementation with contiguous memory -> 10% speedup

**Comment by N-Wouda** [comment]
I do not know about the functional enhancements, but re. fixing existing implementation:

>Corrected problematic bugs, integer overflow, division by zero, looping order-sensitive over unordered set (I assume these have all been fixed here as well?)

I'm pretty sure we have fixed most of these along the way as well. To really make sure we need a bit more detail, but Valgrind is happy (other than the case in #113). We use an unordered set only in SREX, and then just for membership tests - not for iteration. So I think we do not have these problems any more.

>Rewrite recursive calls that were not inlined (5-10% improvement)

I cannot quickly think of a place where we use recursion, other than in `TWS::merge` at compile-time. @wouterkool @leonlan do you know other cases?

>Swap data structures, remove o(n) search by o(1) lookup (not sure what is meant exactly, maybe searching for the first empty route in local search?)

I think this one relates to their changes in `Individual`: they switched the proximity structure from a `std::map` to a `std::unordered_map`. But that's from logarithmic to constant time, not lineaar to constant. We currently have something that's basically logarithmic for the proximity structure.

If it's that change in `Individual`, then this is part of something that currently takes <0.5% of runtime in PyVRP, and is probably not worth tinkering with.

>Matrix in 2D array implementation with contiguous memory -> 10% speedup

We should try this; it would basically be a free performance improvement if it works as advertised.

**Comment by N-Wouda** [comment]
@wouterkool do you know when Kleopatra's code is going to be made available?

**Comment by N-Wouda** [comment]
@wouterkool @leonlan is there anything in this list that we (a) do not yet have, and (b) actually want to have? If so, I propose we split those items off into separate issues and close this one.

**Comment by leonlan** [comment]
None from my side!

**Comment by wouterkool** [comment]
I think these contain some nice ideas that could improve performance but if we do not consider that a priority I do not see it happening anytime soon. Maybe an issue is not the place for it but would it be nice to keep somewhere a list of ideas for potential performance improvements?

**Comment by wouterkool** [comment]
Except maybe the 2D matrix, if the claim is correct that seems relatively simple yet significant so it may be worth implementing anyway.
