### ISSUE TITLE
Greedy repair with penalized costs

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#182]
We currently have the `crossover::greedyRepair` function to repair incomplete offspring solutions after replacing routes in SREX. This greedy repair operator only naively takes into account (in)feasibility due the time windows.

It would be nice to have a greedy repair operator that uses the `Node` and `Route` structures to compute penalized costs, similar to how the local search operators work. This can then be used for developing ruin-and-recreate based algorithms such as (A)LNS.

**Comment by N-Wouda** [comment]
I think we now mostly have this.

**Comment by leonlan** [comment]
I don't see where we have this already, are you referring to `crossover::greedyRepair` or `LocalSearch::maybeInsert`?

**Comment by N-Wouda** [comment]
`crossover::greedyRepair`

**Comment by leonlan** [comment]
That also means we should allow Individuals to be constructed without all required customers. 

https://github.com/PyVRP/PyVRP/blob/8dc237b47ce515116f1ebd8641da3f29afcff8d1/pyvrp/cpp/Individual.cpp#L128-L135

and maybe add an attribute `hasAllRequiredClients` which should also be included in `Individual::isFeasible`.

**Comment by N-Wouda** [comment]
> That also means we should allow Individuals to be constructed without all required customers.

I'm already working on LNS support, so that should be OK now.

**Comment by N-Wouda** [comment]
From #305: I think we can put `greedyRepair` or similar in a `pyvrp.repair` module. That module can then host our LNS repair operators. Another repair operator can be based on our local search. We should be able to make that work with very limited modification.

To make that work we need to decide what a `RepairOperator` should look like, while taking into account we'll probably want to use `greedyRepair` in `crossover` as well.

**Comment by N-Wouda** [comment]
I'm going to finish up my other open PRs and then try to work on this, because it's somewhat of a blocker for both #305 and #307, both of which I want to see completed soon.
