### ISSUE TITLE
Can we directly pass distance/time matrix as input to the ProblemData?

### ISSUE THREAD

**Issue by pravin4u** [PyVRP/PyVRP#184]
I always wonder can we directly pass distance/time matrix as input to the ProblamData instead of current co-ordinates informations. I guess it will results in different set of routes. Any suggestions! Thank you!

**Comment by leonlan** [comment]
> I always wonder can we directly pass distance/time matrix as input to the ProblamData instead of current co-ordinates informations. I guess it will results in different set of routes. Any suggestions! Thank you!

Hi @pravin4u, yes this is possible. You can instantiate a `ProblemData` object similar to how it's done as in https://github.com/N-Wouda/PyVRP/blob/main/pyvrp/read.py.

**Comment by leonlan** [comment]
@N-Wouda @wouterkool What do you think of adding the `**kwargs` argument in `read.py` to let users pass along custom data? This may also be needed for #185, where we need to restrict the number of vehicles to one because this is not specified in TSPLIB instances.

We then also need to validate the data in ProblemData/solve this TODO: 
https://github.com/N-Wouda/PyVRP/blob/dab02952ff70daedafcf81ab38d79805d2af3994/pyvrp/cpp/ProblemData.cpp#L32

**Comment by wouterkool** [comment]
I think if a user wants to customize the distance matrix, they can just implement their own version of `read`, or (simple but not so pretty) use read and then create a copy of `ProblemData` with their own distance matrix.

To support TSPLIB, we can either separate `read` into `read_vrp` and `read_tsp` or make the function work for both cases (dependigng on how the VRPLIB library handles this), but I don't think we need to support passing in parameters externally, precisily for this use case we support instantiating the `ProblemData` object directly from Python.

**Comment by leonlan** [comment]
Following our discussion from yesterday, we are not going to add keyword arguments to `read.py`.

**Comment by N-Wouda** [comment]
> Can we add a maximum traveled distance constraint to each vehicle route in the current pyvrp library?

Not currently, but something like this (based on max duration and shift durations/time windows) is planned for the near future!

**Comment by N-Wouda** [comment]
@pravin4u this was merged into main just yet through #209. It'll make its way to the version on PyPI in the coming weeks!

**Comment by N-Wouda** [comment]
> Can we add a maximum traveled distance constraint to each vehicle route in the current pyvrp library? Big shout-out to the team for past suggestions and future.

Maximum route duration is a constraint that PyVRP now also supports. It was added in v0.7.0, released a few weeks ago!
