### ISSUE TITLE
Penalty updates

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#193]
We currently update penalties as follows:

    auto const diff = params.targetFeasible - feasPct;

    if (-0.05 < diff && diff < 0.05)  // allow some margins on the difference
        return penalty;               // between target and actual

    auto dPenalty = static_cast<double>(penalty);

    // +- 1 to ensure we do not get stuck at the same integer values, bounded
    // to [1, 1000] to avoid overflow in cost computations.
    if (diff > 0)
        dPenalty = std::min(params.penaltyIncrease * dPenalty + 1, 1000.);
    else
        dPenalty = std::max(params.penaltyDecrease * dPenalty - 1, 1.);

    return static_cast<int>(dPenalty);

where `dPenalty` is the new penalty value. This is being moved to Python as part of #100, but for now I'm using the equivalent C++ code.

I see a few issues/directions we can go in:
- Why is the target margin hardcoded at `0.05`? Can we give that thing a name and put it somewhere, or we can get rid of this value entirely by scaling the penalty update based on the distance from the target?
- Why are the penalties integral? This is only needed to evaluate an integral objective/delta cost, but the penalties themselves can just be floats.
- Are there simple policies in the control literature for managing such penalties that might work better than this thing? Keeping something within two bounds by toying with another value is a common problem, surely we can find something for this that's not as heavy as, say, MPC (the only control thing I know well). This could be a cool research direction.

**Comment by wouterkool** [comment]
Some thoughts:
* If penalties are float, but objectives are integral, we may get inconsistencies, i.e. if new_cost = cost + delta, it does not mean round(new_cost) = round(cost) + delta, which may cause unwanted subtleties in the code. I guess that is why you changed it to integral previously? They were doubles [here](https://github.com/ortec/euro-neurips-vrp-2022-quickstart/blob/main/baselines/hgs_vrptw/Params.h#L125))
* I agree we could probably simplify things but I would need to think a bit on what would be a sensible approach. However, I am not sure if/how a general control algorithm can use the useful prior knowledge that a large penalty results in more feasible solutions.

**Comment by N-Wouda** [comment]
>Why is the target margin hardcoded at 0.05? Can we give that thing a name and put it somewhere, or we can get rid of this value entirely by scaling the penalty update based on the distance from the target?

Probably, yes. Scaling the update by distance to target would smoothen the penalty changes a lot, which @leonlan has found to be useful for e.g. HFVRP.

We can also make the penalty increase/decrease updates each other's inverses if we do this. That'd leave us with a single parameter to control the updates, rather than three right now (penalty increase, decrease, and the 5% feasibility tolerance). Seems simpler to tune.

**Comment by N-Wouda** [comment]
Re-opening this based on what Leon and I discussed just yet.

**Comment by N-Wouda** [comment]
Assigning this for 0.9.0. Could be good to work on after #594 / #607.

**Comment by N-Wouda** [comment]
This overhaul could include a bit of tuning for the penalty parameter. I suspect a range of, say, $(1, 1.05, \ldots, 1.5)$ will be sufficient.

**Comment by N-Wouda** [comment]
I want to reconsider a bit whether we actually need such a clunky updating method that looks at, say, the last 50 iterations, averages those, and then increases or decreases the penalty term by fixed amounts. This is just another optimisation/control problem and we might be able to do something slightly smarter.

**Comment by N-Wouda** [comment]
I ran the `PR11A` instance for 20K iterations, and logged every 50 iterations what the TW penalty value and the average percentage of feasible solutions over the last 50 iterations was. The results are in this figure:
![image](https://github.com/PyVRP/PyVRP/assets/16272507/68be6f55-547d-4376-be36-4dab7908d69d)

This doesn't tell the whole story, but the following is interesting:
- Evaluations of "average feasible solutions" for a single penalty value is super noisy;
- We are skipping values because of our current update system. That might be problematic;
- Although the observations are noisy, the monotonicity is pretty clearly visible - we know higher penalty == higher average feasible.

**Comment by N-Wouda** [comment]
To check: can we let the penalties go to zero, and skip evaluations based on that in the `CostEvaluator`?

**Comment by N-Wouda** [comment]
I wanted to have a look at this for 0.9.0. But if we switch to ILS in 0.10.0, I think it's worth the time to figure out what the role of the penalties is going to be in that algorithm before we do a lot of rework here.

So unassigning this from 0.9.0 for now.

**Comment by N-Wouda** [comment]
I think #711 already dealt with a large part of this issue.
