### ISSUE TITLE
Use std::limits in XorShift128.cpp

### ISSUE THREAD

**Issue by wouterkool** [PyVRP/PyVRP#197]
Rather than UINT_MAX we should use `std::numeric_limits<>::max()`. However, should we use `std::numeric_limits<unsigned int>::max()` to keep the value the same or `std::numeric_limits<size_t>::max()` to be consistent with the return type (`size_t` is `unsigned long`)? @N-Wouda

**Comment by N-Wouda** [comment]
I'm not sure what the context of the question is. Do you mean in `XorShift128`? There the return type is wrong, that should be `XorShift128::result_type`, with `std::numeric_limits<result_type>::max()`.

**Comment by N-Wouda** [comment]
In general everything using the macros `*_MIN` and `*_MAX` should probably be using `std::numeric_limits`.
