### ISSUE TITLE
Modelling API/how to build an instance

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#217]
Right now, we build a `ProblemData` instance in one go, from a list of clients (incl. the depot), some vehicle data, and the distance and duration matrices. This works, but we for example assume the depot is at index `0` in the matrices, and that the depot is the "0-th client". That's all somewhat odd/implicit, and we assume users to get this right. The current interface is similar to how [OR-Tools](https://developers.google.com/optimization/routing) does it as well. So we're definitely in good company.

I think we can do better if we offer an incremental problem-building API with methods like `add_depot()`, `add_client()`, `add_edge()`, etc. This is for example how [VRPSolverEasy](https://github.com/inria-UFF/VRPSolverEasy) works, and the examples there are really neat. E.g., from their README:
```python
# Add vehicle type
model.add_vehicle_type(
    id=1,
    start_point_id=0,
    end_point_id=0,
    name="VEH1",
    capacity=1100,
    max_number=6,
    var_cost_dist=cost_per_distance,
    tw_end=5000)

# Add depot
model.add_depot(id=0, name="D1", tw_begin=0, tw_end=5000)

coordinates_keys = list(coordinates.keys())
# Add customers
for i in range(1, nb_point):
    model.add_customer(
        id=i,
        name=coordinates_keys[i],
        demand=demands[i],
        tw_begin=begin_time,
        tw_end=end_time)

# Add links
coordinates_values = list(coordinates.values())
for i in range(0, 7):
    for j in range(i + 1, 7):
        dist = compute_euclidean_distance(coordinates_values[i][0],
                                          coordinates_values[j][0],
                                          coordinates_values[i][1],
                                          coordinates_values[j][1])
        model.add_link(
            start_point_id=i,
            end_point_id=j,
            distance=dist,
            time=dist)
```
I like this idea, but am not overly fond of e.g. the use of a user-defined ID for linking. Nonethess, I think offering an API of this form lets us decouple the internal organisation of clients/depots and distance/duration matrices from the problem definition users are supposed to provide, and thus lets us hide a few more details. The precise form of the problem-building API we can then hash out later.

**Comment by leonlan** [comment]
I also like the VRPSolverEasy interface!

> I like this idea, but am not overly fond of e.g. the use of a user-defined ID for linking.

Curious to hear why you are not overly fond of this idea. If we let users pass the distances and duration matrices, then they will also have to provide the corresponding location index / ID to access these values. I don't directly see how we could do this in another, better way.

**Comment by wouterkool** [comment]
I agree this would be helpful. I do however like the idea of ProblemData being immutable, to avoid users changing the data, e.g. in between calls to LocalSearch. We could use something like a Builder pattern to support that?

Also related, I thought it would be nice if we could integrate nicely with VRPSolverEasy e.g. by supporting conversion from/to their problem format (if we support the constraints), which would really easy benchmarking.
