### ISSUE TITLE
Crossover for TSP

### ISSUE THREAD

**Issue by wouterkool** [PyVRP/PyVRP#235]
When using PyVRP to solve a TSP (a VRP with a single route), I think the SREX crossover will simply return one of the parents as offspring. As these are already locally optimal, the local search will not improve and the algorithm will get stuck. 

I did think of this issue, not validate it experimentally. Not sure if this is a bug or just unsupported either.

Some thoughts would be to have a different crossover for a single route.

**Comment by leonlan** [comment]
This can definitely be solved by implementing #159 (and maybe #231?).

**Comment by N-Wouda** [comment]
We might want to
- Add tests that exercise SREX for TSP solutions, to verify it indeed returns one of the given parents;
- Add a warning that SREX is ineffective when `data.num_vehicles == 1`.

**Comment by N-Wouda** [comment]
I'm pretty sure #422 runs into this issue 😆. Let's add some tests to check this and confirm our suspicion. I'll do that tomorrow.

Then we need some way to fix the issue. Perhaps have a simple ordered crossover? I'm personally fine with that only working for the case where `data.num_vehicles() == 1` - for the other cases SREX is typically much better anyway.

**Comment by N-Wouda** [comment]
Anyway @wouterkool @leonlan it seems like we'll have to resolve this open issue now.

**Comment by N-Wouda** [comment]
> Not sure if this is a bug or just unsupported either.

My two cents: I consider this to be a bug, since a VRP with just one vehicle is neither rare nor unexpected. We should be able to handle that without complaints.

**Comment by leonlan** [comment]
If we assume that the number of vehicles is one, then a simple ordered-crossover (OX) could already work. We already have code for that and we don’t need to deal with splits since we only use it in the 1 vehicle case.

**Comment by N-Wouda** [comment]
Since you've come to the same conclusion, I'll write up a draft PR for this soon. Possibly today, depending on how some other things go.

**Comment by wouterkool** [comment]
I fully support the conclusion :) let's do OX for TSP. Now question is if we want to make the user responsible of selecting the right crossover for the right problem or if we should somehow do that automagically? If not, at least a warning/error should suggest the user to use a different crossover, but it would be nice if the high-level Model API just works I guess?
