### ISSUE TITLE
Rename some stuff to make it less dependent on HGS terminology

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#239]
Particularly
- [x] `Individual` to `Solution`
- [x] `pyvrp.educate` to `pyvrp.improve`? Or `pyvrp.search`?

For the latter I think I prefer `pyvrp.search`: `LocalSearch` fits the bill already, and a future `LargeNeighbourhoodSearch` or `VariableNeighbourhoodSearch` will also work.

**Comment by leonlan** [comment]
I like `search`!
