### ISSUE TITLE
Heterogeneous fleet: instances and solutions

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#252]
From #245:

- [x] How to read heterogeneous instances and solutions
- [x] How to print heterogeneous solutions. Do we include vehicle type?
- [x] Whether we can remove `make_heterogeneous` helper [yes, done]
- [x] Do we need benchmark instances for heterogeneous capacity? [no, covered by other instances]

**Comment by N-Wouda** [comment]
@leonlan especially the first item relates to VRPLIB. Do you know if there's any standard for, say, a `VEHICLE_SECTION`?

**Comment by leonlan** [comment]
> @leonlan especially the first item relates to VRPLIB. Do you know if there's any standard for, say, a `VEHICLE_SECTION`?

I'll look into this in the coming week. As far as I know, TSPLIB/VRPLIB only considers homogeneous vehicle problem instances. I don't think there's a standard for a vehicle section, but I'll try to think of something.

**Comment by leonlan** [comment]
I have not found any VRPLIB-related datasets that specify vehicle characteristics, so we need to come up with our own solution for this. I propose to introduce `VEHICLE_CAPACITY_SECTION`, which specifies the capacity for each vehicle. We can group by unique vehicle capacities to define vehicle types.

**Comment by leonlan** [comment]
> Do we need benchmark instances for heterogeneous capacity?

There are not many benchmark instances for heterogeneous capacity. Based on the paper by Maximó, there are 18 instances with $n<120$ customers and 10 instances with $n \in [150-350]$. I don't really think it's worthwhile to benchmark this.

**Comment by yang0824** [comment]
Is there a solution for the heterogeneous capacity problem in pyvrp now?

**Comment by N-Wouda** [comment]
> I propose to introduce `VEHICLE_CAPACITY_SECTION`, which specifies the capacity for each vehicle. We can group by unique vehicle capacities to define vehicle types.

@leonlan I think this is the best long-term way to support multiple capacities. We can parse and group this ourselves when reading. Does this need changes to VRPLIB to work? I'm assuming no.

**Comment by leonlan** [comment]
Nope, no changes are needed.

**Comment by N-Wouda** [comment]
Alright then I think we should pick this up sometime soon to generate a few instances for the unit tests.

**Comment by wouterkool** [comment]
I think it's fine to introduce `VEHICLE_CAPACITY_SECTION`, but on the other hand do we really need to support that? Given that (I think) there is no existing data, users will have their own existing format or generate their own data, in which case I'm not sure if it makes sense to convert to some extension of VRPLIB which I think is not the best format either. Also keep in mind that we should probably add support for heterogeneous costs as well as heterogeneous capacities without heterogeneous costs are a bit weird as well.

**Comment by leonlan** [comment]
While VRPLIB is not the best format, I think it's easy to understand and works fine for simple VPR variants. LKH-3 already has introduced many extensions to VRPLIB and I don't think it hurts to extend this even further for our own purposes, namely benchmarking and testing.

**Comment by N-Wouda** [comment]
For MDVRPTW, we need the following sections:
```
VEHICLE_TYPE_NUMBER_AVAILABLE_SECTION
VEHICLE_TYPE_CAPACITY_SECTION	
VEHICLE_TYPE_DEPOT_SECTION
VEHCILE_TYPE_MAXIMUM_DURATION_SECTION
```

**Comment by N-Wouda** [comment]
I suggest (for somewhat backwards compatibility):
```
VEHICLES_SECTION (not VEHICLE_TYPE_NUMBER_AVAILABLE_SECTION)
CAPACITY_SECTION (not VEHICLE_TYPE_CAPACITY_SECTION)
```
since those specifications currently already have those names.
For the other two, perhaps:
```
VEHICLES_DEPOT_SECTION
VEHICLES_MAX_DURATION_SECTION
```

**Comment by leonlan** [comment]
Could you point me to the instances that have a VEHICLES_SECTION and CAPACITY_SECTION? (out of curiosity)

**Comment by N-Wouda** [comment]
> Could you point me to the instances that have a VEHICLES_SECTION and CAPACITY_SECTION? (out of curiosity)

They aren't used. The `VEHICLES` and `CAPACITY` _specifications_ are used, however. `vrplib` strips the section suffix, so these sections would result in the same key being used as those earlier specifications in the return value from `vrplib`. I think that's pretty neat.

**Comment by leonlan** [comment]
Ah right, yeah that works. But what is the meaning behind `VEHICLES_SECTION`? Since your proposal is to track actual vehicle data rather than vehicle type data, there is no longer a need for `VEHICLES_SECTION` and instead the `VEHICLES` specification suffices. 

By the way, I agree with tracking vehicle data instead of vehicle type data.

**Comment by N-Wouda** [comment]
> Ah right, yeah that works. But what is the meaning behind `VEHICLES_SECTION`? Since your proposal is to track actual vehicle data rather than vehicle type data, there is no longer a need for `VEHICLES_SECTION` and instead the `VEHICLES` specification suffices.

Yes, sorry, I had missed that. Good point, and nice that we indeed do not really need to change this.
I'll try to work out the details of this in a PR soon, so that we can start benchmarking MDVRPTW.

**Comment by N-Wouda** [comment]
How do we write solution files with route/vehicle ties? Our `VehicleType` does not know which vehicles are grouped into it, and can thus not 'translate' back to the original problem instance.

**Comment by leonlan** [comment]
One option is to assume that the vehicle data is grouped (e.g., vehicles 1-5 to the same type, vehicles 6-10 belong to the same type, etc.). Then, we first sort the solution's routes on vehicle types and print each individual route. The only catch is that we don't allow for empty routes (not sure when/if we will address #389) so we need to also add empty routes.

**Comment by N-Wouda** [comment]
I think we have already figured this one out by just doing it the same way we do it for MDVRPTW - print the empty routes as well. So I'm closing this issue. We still have #188 for the algorithmics.
