### ISSUE TITLE
Describe HFVRP and VRP-RT in documentation

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#258]
Now that #254 is implemented we should add VRP with release times to the list of supported VRP variants [here](https://pyvrp.readthedocs.io/en/latest/setup/introduction_to_vrp.html).

**Comment by leonlan** [comment]
Also: heterogeneous capacitated vehicles

**Comment by N-Wouda** [comment]
Also update README with a list of stuff we can handle. I'm going to work on that probably this weekend (together with #259).

**Comment by leonlan** [comment]
It's already somewhat "documented" in the list of stuff that we can handle. I don't feel like adding it to https://pyvrp.readthedocs.io/en/latest/setup/introduction_to_vrp.html adds much benefit since these variants are too small on themselves. 

After we support more variants (v0.9.0 or (v0.10.0) we should turn #441 into documentation.
