### ISSUE TITLE
Example notebooks

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#259]
With all the features that we implemented over the past month, I think it's a good moment to re-think about what kind of example notebooks we want.

Ideas:
- [x] **Model interface**: One notebook demonstrating the use of the `Model` interface, and how it can be used to solve different variants of VRPs (CVRP, VRPTW, PC-VRP, HF-VRP, VRP-RT, etc.). The target audience is users interested in solving VRPs but with little experience in building algorithms.
- [x] **Custom genetic algorithms**: showcasing how to customize a genetic algorithm to solve a single VRP variant (e.g., VRPTW). The target audience for this notebook is users interested in customizing the genetic algorithm for research or performance purposes. Examples are using different crossovers, and other (local) search strategies.
- [ ] **Other (meta-)heuristics**: showing users how to use PyVRP components to build their own VRP algorithm, like Iterated Local Search.

Questions:
- We currently have two example notebooks: one for [VRPTW](https://pyvrp.readthedocs.io/en/latest/examples/vrptw.html) and one for [CVRP](https://pyvrp.readthedocs.io/en/latest/examples/cvrp.html). What do we want to do with these notebooks? I suggest re-using some parts of these notebooks for the new suggestions above. I find these notebooks on themselves are not very useful for users.

Other ideas/suggestions?

**Comment by N-Wouda** [comment]
First one yes, definitely, as a really simple introduction. We can have a look at how e.g. OR-Tools does this. Their intro is pretty good. This needs to be really accessible, much more so than the current notebooks.

Second: yes, as a more in-depth notebook to complement the high-level one using the modelling interface. Can re-use quite a bit from the existing notebooks, but should have much more descriptive text explaining how things work.

Third: sure? I don't mind having such a notebook, but I am not going to write it myself.

**Comment by N-Wouda** [comment]
I'll have a go at the first two soon.

**Comment by N-Wouda** [comment]
I'm unassigning myself because the two items I wanted to do for this issue have been completed in #266.

**Comment by leonlan** [comment]
I don't think it's necessary to have the third item, because it's already clear from https://pyvrp.org/examples/using_pyvrp_components.html how to use PyVRP components to build a custom algorithm. So I consider this issue to be done.
