### ISSUE TITLE
New documentation theme

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#270]
The RTD theme has some issues, see details below about margins in example notebooks:
<details>
<summary><b>Margins in example notebooks</b></summary>
Unlike regular text blocks, code blocks have zero margins at the bottom. For a sequence of code blocks, this looks fine.

But when for notebooks where code and text are continuously alternating (for example PyVRP components), this results in the following:
![image](https://github.com/PyVRP/PyVRP/assets/30997278/90269c71-fe1e-4fa5-9cdb-8fd71ca6f203)

This looks a bit too compressed to me. I'd want to see some margins between the code block and the subsection header. And also some margin between the code block and the next paragraph. For example:
![image](https://github.com/PyVRP/PyVRP/assets/30997278/41b50860-5bbb-4442-a18e-c91d59d0bcc4)

Increasing the bottom margin of code blocks "fixes" this problem, but it makes a sequence of code blocks look ugly. 
I think the solution is to add some top margin to paragraphs and sections headers (for h3 and smaller, h1-h2 already have some marigns at the top).
</details>

This issue serves to discuss using a new documentation theme.

**Comment by N-Wouda** [comment]
I really don't want to tinker with this in e.g. CSS. The RTD theme we currently use has more warts, like rendering lists that's really finnicky. We might be able to just switch themes, for example to [sphinx_immaterial](https://jbms.github.io/sphinx-immaterial/), which statsmodels and ruff also use.

**Comment by leonlan** [comment]
> I really don't want to tinker with this in e.g. CSS, mostly because it's really tedious to write and maintain, and annoyingly ties us to a particular theme. The RTD theme we currently use has more warts, like rendering lists that's really finnicky. We might be able to just switch themes instead? An alternative is [sphinx_immaterial](https://jbms.github.io/sphinx-immaterial/), which statsmodels and ruff also use.

Another theme is also fine by me (and something I have considered before). I'll update the issue to be about choosing a new theme. 

Sphinx Immaterial looks good to me, and based on the statsmodels examples, the notebooks are rendered nicely.

**Comment by N-Wouda** [comment]
I'll have a go at this!
