### ISSUE TITLE
Solving error due to empty neighbourhood in single client instance

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#272]
#### Describe the bug

I'm solving an instance with one depot and one client through the `Model` interface. When trying to solve this instance, the solver raises a RuntimeError because the default neighbourhood of such an instance is empty.

#### Code sample

```python
import matplotlib.pyplot as plt

from pyvrp import Model
from pyvrp.plotting import plot_coordinates, plot_solution
from pyvrp.stop import MaxRuntime

COORDS = [
    (456, 320),  # location 0 - the depot
    (228, 0),    # location 1
]
DEMANDS = [0, 1]

m = Model()
m.add_vehicle_type(capacity=15, num_available=1)
depot = m.add_depot(x=COORDS[0][0], y=COORDS[0][1])
clients = [
    m.add_client(x=COORDS[idx][0], y=COORDS[idx][1], demand=DEMANDS[idx])
    for idx in range(1, len(COORDS))
]

locations = [depot, *clients]
for frm in locations:
    for to in locations:
        distance = abs(frm.x - to.x) + abs(frm.y - to.y)  # Manhattan distance
        m.add_edge(frm, to, distance=distance)

res = m.solve(stop=MaxRuntime(1))  # one second
```

Running this in a clean Colab session produces the following error:
```python
[/usr/local/lib/python3.10/dist-packages/pyvrp/search/LocalSearch.py](https://localhost:8080/#) in __init__(self, data, rng, neighbours)
     26         self, data: ProblemData, rng: XorShift128, neighbours: List[List[int]]
     27     ):
---> 28         self._ls = _LocalSearch(data, neighbours)
     29         self._rng = rng
     30 

RuntimeError: Neighbourhood is empty.
```

I'm using version 0.4.4:
```python
INSTALLED VERSIONS
------------------
     pyvrp: 0.4.4
     numpy: 1.22.4
matplotlib: 3.7.1
    vrplib: 1.1.0
      tqdm: 4.65.0
     tomli: 2.0.1
    Python: 3.10.12
```

#### Expected Output
I expect that:
- instances with one depot and at least one client can be solved, or
- we raise an error when `Model.solve` is called when the number of clients is less than two.

**Comment by N-Wouda** [comment]
I think the appropriate way forward is explicitly adding the depot to the neighbourhood structure. That'll require some changes to the local search as well, but seems to me the cleanest approach. And it'd also tackle #154.

**Comment by leonlan** [comment]
> or: allow empty neighbourhoods. I opened a PR a while back that partially tackled this (https://github.com/PyVRP/PyVRP/pull/176), but never got around to finishing that.

Any particular reason why this PR was closed?

> This to me seems wrong, because a one client instance is an appropriate VRP. It's absolutely trivial, yes, but it is a VRP nonetheless.

What is our definition of a VRP instance? At least one depot and at least one client?

**Comment by N-Wouda** [comment]
> What is our definition of a VRP instance? At least one depot and at least one client? I think we should maybe also handle the case in which there are no clients defined.

I don't really know. I guess an empty instance is also an instance, so yeah, nothing is also OK I guess?

**Comment by leonlan** [comment]
I'm going to try allowing empty neighborhoods.
