### ISSUE TITLE
Heterogeneous Vehicle Routing Problem

### ISSUE THREAD

**Issue by yang0824** [PyVRP/PyVRP#277]
Is there a solution for the heterogeneous capacity problem in pyvrp now?

**Comment by N-Wouda** [comment]
Yes, that was introduced in PyVRP 0.4.0, released a few weeks ago. You can add multiple vehicle types with different numbers of vehicles and capacities to your problem, and then PyVRP will use those. Only capacities can differ between vehicles for now; other vehicle attributes are not (yet) implemented.
