### ISSUE TITLE
Fleet management

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#31]
From discussion: we should add a feature that supports fleet management via e.g. a hierarchical objective. We can provide some sort of class for this.

**Comment by N-Wouda** [comment]
This has to happen for SINTEF. I'll write a bit more here later today.

**Comment by N-Wouda** [comment]
OK so something using an "on feasibility" stopping criterion could work. That thing terminates the moment we have a first feasible solution. 

The algorithm is as follows.
We set the number of vehicles to a sufficiently large value that we're sure there's a feasible solution. Once a feasible solution has been found, set vehicles - 1 and try again.
At some point we'll not find a feasible solution in e.g. ten minutes. Then terminate with vehicles + 1 as the best-found number of vehicles.
We can use that number for a full SINTEF evaluation run.

**Comment by wouterkool** [comment]
Some thoughts on this:
* maybe to determine how long we should try to find a feasible solution, we could run all SINTEF cases with the BKS num routes as num vehicles and measure how long it takes to find a feasible solution over a few seeds? Then we could set a value that is a nice trade-off in time vs prob of finding minimum number of vehicles.
* not sure how often we attain a lower bound (e.g. based on demand vs vehicle capacity) but it may be worth stopping based on this

**Comment by N-Wouda** [comment]
The more I think about this issue the less I want to do it. The hierarchical objective is nice, but not something we really care about outside of the SINTEF thing. It'd need quite a bit more code to support, and I don't really see any value in that in the long run.

What if we decide this is a *non*-goal? The argument "we do routing, not fleet minimisation" is pretty strong. We can then probably just 'cheat' and use the current best number of vehicles if we're explicit about the why in the paper.

**Comment by wouterkool** [comment]
I think it's nice if it's not too difficult but I don't see a real need either in the homogeneous case. I could use it for heterogeneous fleet, but then it is also (much) more complex. I'm ok with the decision not to implement it now.
