### ISSUE TITLE
Fix/update figure introduction to VRPs docs

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#348]
The figure on the [Introduction to VRPs](https://pyvrp.org/setup/introduction_to_vrp.html) page is not showing up. It is, however, included in the [source code](https://github.com/PyVRP/PyVRP/blob/main/docs/source/setup/introduction_to_vrp.rst).

Also: the figure needs to be updated to work well with the new dark mode theme.

**Comment by N-Wouda** [comment]
I think a `:figwidth: 100%` is sufficient, just like the index page for the PyVRP logo.

**Comment by N-Wouda** [comment]
I'm going to do some work on the developing/contributing docs, so I'll probably add the figwidth there as well. A new image I'll leave for you @leonlan - my photoshop skills are not the best haha.

**Comment by N-Wouda** [comment]
I don't think the current figure looks all that bad. #350 fixes the display issue by setting a figwidth.

**Comment by leonlan** [comment]
> I don't think the current figure looks all that bad. #350 fixes the display issue by setting a figwidth.

Yeah, it doesn't look that bad. I'll try it out with the depot white background removed.

**Comment by leonlan** [comment]
I guess it's nicer to keep the white background.

![image](https://github.com/PyVRP/PyVRP/assets/30997278/6684cb34-b6e2-4b81-802d-0e5abcb2dd38)

(See detail below for the SVG file)
<details>
<summary>Details</summary>

![introduction-to-vrp](https://github.com/PyVRP/PyVRP/assets/30997278/63e04760-7a24-473d-9e44-d601d56a095a)


</details>

**Comment by N-Wouda** [comment]
<img width="1216" alt="image" src="https://github.com/PyVRP/PyVRP/assets/16272507/d31f6871-7bb5-41d0-9d30-6f7173ac2bfd">
At least it shows up again :-)

**Comment by leonlan** [comment]
Let's keep it as-is!
