### ISSUE TITLE
Remove parameters from table of contents in API reference

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#361]
#### Is your feature request related to a problem? Please describe
It's somewhat hard to navigate the API reference, especially https://pyvrp.org/api/pyvrp.html. Part of this is due to the table of contents being cluttered with parameters.

#### Describe the solution you'd like
I propose to remove parameters from table of contents. I think that already improves the navigation a lot.

**Comment by leonlan** [comment]
We are currently using `napoleon` and `numpydoc` at the same time. They kind of do the same thing and sometimes conflict with each other. We should just choose one ([like statsmodels does](https://github.com/statsmodels/statsmodels/blob/56e9c569fadb2805eeb3c64989ea122ea85a95af/docs/source/conf.py#L43)). I'm going for `numpydoc`.

It seems that we are making use of `napoleon` for this option specifically:
```python
napoleon_include_special_with_doc = True
```

**Comment by N-Wouda** [comment]
I think `napoleon` is a bit more recent, more complete, and is built into Sphinx. Those are good reasons to switch to that instead, because it'll let us remove a dependency.

I'm not sure how these two settings work in Napoleon:
```
numpydoc_xref_param_type = True
numpydoc_class_members_toctree = False
```
