### ISSUE TITLE
Remove overload GreedyRepair

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#362]
@N-Wouda We no longer use greedy repair in SREX, so we can remove the overloading of greedy repair right?

https://github.com/PyVRP/PyVRP/blob/2ee203c633130bb3c5d38182f5e184dd8d4681ff/pyvrp/cpp/repair/greedy_repair.cpp#L77-L122

**Comment by N-Wouda** [comment]
Only problem with that is that we can then never insert new routes via greedy repair (since `Solution` does not allow empty routes). We might want to keep it just for that sake.
