### ISSUE TITLE
Out of tree tests?

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#373]
Right now, we have our tests directly next to the source code they test. That's nice, but does mean we also need to put our fixtures in the source tree. We might want to switch to a separate `tests/` tree, such that testing and source code are completely separated. 

A particular case that motivates this is the `pyvrp/conftest.py` file, which should not really be there. Not super high-priority, but we might want to do this at some point.

**Comment by leonlan** [comment]
Suggestion: we should maybe also split up large test files. For instance, `test_Solution.py` is now 866 lines long covering tests for `Route`, `Solution` and `VehicleType`.  

Having separate files named `test_Solution`, `test_VehicleType` and `test_Route` would make it easier to navigate the tests.
