### ISSUE TITLE
Binaries for ARM-based OS X

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#378]
We do not currently provide pre-compiled binaries for ARM-based OS X machines. We might want to do that, but we'd have to cross-compile from the x86 runners GitHub Actions currently supports. That should be possible, I think, based on this: https://cibuildwheel.readthedocs.io/en/stable/options/#archs.

**Comment by leonlan** [comment]
Yea I got an M1 processor (ARM), let me know how I can help with this.

**Comment by N-Wouda** [comment]
I think it's easiest if we just run the CD for a bit, and you check if the resulting wheels are installable on your machine. We could do that synchronously during a call sometime so we can debug stuff as it shows up. There's no real time pressure on this though, so we'll see when :-).
