### ISSUE TITLE
Switch the VRPTW instances over to VRPLIB format

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#390]
Our VRPTW instances are in Solomon format. All others are VRPLIB-formatted, including the prize-collecting instances which extend the VRPTW instances. For consistency, I think we can just format all instances in VRPLIB format, and use the `.vrp` extension.

**Comment by N-Wouda** [comment]
@leonlan would there be any reason *not* to do this? I know Keld Helsgaun for example also did the same thing with his versions of the GH1000 instances - those are all in VRPLIB format.

**Comment by leonlan** [comment]
There is no reason not to do this. The only suggestion that I have when using Keld Helsegaun's VRPTW instances is that we remove the `SERIVCE_TIME : 90` specification and make it a data section instead.

**Comment by N-Wouda** [comment]
> The only suggestion that I have when using Keld Helsegaun's VRPTW instances is that we remove the `SERIVCE_TIME : 90` specification and make it a data section instead.

Why do we not want to have a specification? I just noticed our prize-collecting instances also have this (those are based on the same VRPLIB formatted data of Helsgaun).

**Comment by leonlan** [comment]
> > The only suggestion that I have when using Keld Helsegaun's VRPTW instances is that we remove the `SERIVCE_TIME : 90` specification and make it a data section instead.
> 
> @leonlan why do we not want to have a specification? I just noticed our prize-collecting instances also have this (those are based on the same VRPLIB formatted data of Helsgaun).

The service time specification was (presumably) introduced to convert the GH/Solomon instances to VRPLIB style. Since the GH instances had only constant service times, Helsgaun added a specification, but I think the ideal case is to have all client data presented as data sections. The only exception to make is for vehicle data (because a homogeneous fleet is widespread In the VRP literature).
