### ISSUE TITLE
Random solutions use too many vehicles

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#396]
#### Is your feature request related to a problem? Please describe
When initializing random solutions with an instance where `num_vehicles > num_clients`, the client per route uses two clients instead of one. This is problematic when solving constrained instances with unlimited fleet, as this means that the initial random solutions often are infeasible.

<details>
<summary>Example</summary>

```python
from pyvrp import Model
from pyvrp.stop import MaxRuntime
from pyvrp import Solution, RandomNumberGenerator

COORDS = [
    (456, 320),  # location 0 - the depot
    (228, 0),    # location 1
    (912, 0),    # location 2
    (0, 80),     # location 3
    (114, 80),   # location 4
    (570, 160),  # location 5
]
DEMANDS = [0, 1, 1, 2, 4, 2]

m = Model()

m.add_vehicle_type(capacity=15, num_available=6)

depot = m.add_depot(x=COORDS[0][0], y=COORDS[0][1])
clients = [
    m.add_client(x=COORDS[idx][0], y=COORDS[idx][1], demand=DEMANDS[idx])
    for idx in range(1, len(COORDS))
]

locations = [depot, *clients]
for frm in locations:
    for to in locations:
        distance = abs(frm.x - to.x) + abs(frm.y - to.y)  # Manhattan
        m.add_edge(frm, to, distance=distance)

data = m.data()
rng = RandomNumberGenerator(1)
sol = Solution.make_random(data, rng)

[route.visits() for route in sol.get_routes()]
# [[5, 4], [1, 2], [3]]
```

</details>

The problem lies in 
https://github.com/PyVRP/PyVRP/blob/f91937a5cc4565294352e5cd9e5e0d1f1eefcfa9/pyvrp/cpp/Solution.cpp#L121-L127

- The current situation when `num_vehicles <= num_clients` works fine.
- If `num_vehicles > num_clients`, the expression `(numClients % numVehicles != 0)` always evaluates to true hence perRoute will be equal to perVehicle + 1.

#### Describe the solution you'd like

`(numClients % numVehicles != 0)` should be false when `num_vehicles > num_clients`.

**Comment by N-Wouda** [comment]
I'm removing the `bug` label because this is working as intended (we can change the behaviour but it isn't a bug).
