### ISSUE TITLE
Simultaneous pickup and delivery

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#434]
For the next release cycle (so, 0.8.0 or so), I would like to try to get some form of mixed backhaul into PyVRP. Right now we only support deliveries from the depots to the clients, and I would like to also add return shipments from the clients to the depots.

[João Santos et al. (2023)](https://doi.org/10.1016/j.omega.2023.102864) provide an overview of many VRPs with pickup and delivery, including various forms of backhaul.

_Originally posted by @N-Wouda in https://github.com/PyVRP/PyVRP/issues/331#issuecomment-1913578985_

**Comment by leonlan** [comment]
After #471, we should find a set of benchmark instances for a variant of VRPSPD. Some options are:
- [Montané and Galvão (2006)](https://www.sciencedirect.com/science/article/abs/pii/S0305054804001741): 18 VRPSPD instances with [100-400] clients
	- Issue: can't find these instances. I have contacted Anand Subramanian, since he also used this to benchmark ILS-RVND-SP.
	- If we use these instances then we can compare with Vidal et al. (2014).
- [Queiroga et al. 2019](https://www.sciencedirect.com/science/article/pii/S0377221720304008)
	- Instances can be found here: http://www.vrp-rep.org/datasets/item/2019-0003.html
	- We could use these instances instead and compare with a bunch of metaheuristics from https://link.springer.com/article/10.1007/s11590-020-01564-5.

**Comment by N-Wouda** [comment]
I'm keeping this open just until we get some benchmark results in.

**Comment by N-Wouda** [comment]
#482 is related to this - we should figure that one out to get the full benchmark runs in.

**Comment by N-Wouda** [comment]
> * It's 300 instances (3 variants for all 100 X instances), so that's a bit much for a benchmark.

What's the stopping criterion? Intuitively I agree that this is a bit much and we might want to take a subset of these instances for PyVRP, but if the runtime limit is small we might also be able to keep all of them. If not, maybe we should take the ~30 biggest instances for each variant, for a total of 90 instances?

**Comment by leonlan** [comment]
The stopping criterion was unspecified, so I went for the same convention as CVRP/X instances: $2.4 * n$, where $n$ is the number of clients.

That’s an average of 20 minute per instance * 300 instances = 100h. Multiply by 10 seeds and we have 1000h. That’s about the same as VRPTW and PCVRPTW (60 * 2 * 10 = 1200h).

I think taking the 30 biggest instances per category is a good idea!

**Comment by N-Wouda** [comment]
We now have benchmark instances, so I'm closing this issue. We'll need to investigate some of the behaviours further in #482, but that is unrelated to the issue of obtaining benchmark instances in the first place.
