### ISSUE TITLE
Significant performance drop in costs

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#44]
I benchmarked an old version of the code on the EURO-NeurIPS instances, where the `CommandLine.h` was still available. It turns out that we have a significant drop in performance w.r.t. the costs. 

I ran three versions of the repo and computed the results for the qualification phase of the competition. Here are the details:
- 10 January [afcf6bf](https://github.com/N-Wouda/VRP-Solver-IJOC/commit/afcf6bf61407961b3b37a84565f7ea467ca8f9e3)
	- Average cost: 175892
	- Solutions: [230110.zip](https://github.com/N-Wouda/VRP-Solver-IJOC/files/10448362/230110.zip)

- 20 December [50dc497](https://github.com/N-Wouda/VRP-Solver-IJOC/commit/50dc4978d569b6ac2e885d77f06dc99c9b193c35)
	- Average cost: 164357
	- Solutions: [221220.zip](https://github.com/N-Wouda/VRP-Solver-IJOC/files/10448302/221220.zip)

- 14 November [dffe3b5](https://github.com/N-Wouda/VRP-Solver-IJOC/commit/dffe3b5ef49a2bfc53f0f1f5b72b347631c66272)
	- Average cost: 164230
	- Solutions: [221114.zip](https://github.com/N-Wouda/VRP-Solver-IJOC/files/10446957/221114.zip)

For reference, we maintained a [Google spreadsheet](https://docs.google.com/spreadsheets/d/12YMgWxwouHGxOEn_IxHJIOGhzr6WKTsq5lW2mDPu0M4/edit#gid=0) during the competition to track our benchmark results. 

Seems that something went wrong between 4 January and 20 December. @N-Wouda You have probably a better idea what happened here. Any clues where it may have gone wrong? I can try to run a few more benchmarks in binary search style.

**Comment by leonlan** [comment]
Can we make this a priority for the coming week? Leaving this to the last weeks is tricky as we also need time to process the results and put them in the paper. 

I quickly profiled a single run with 10k iterations on instance ``ORTEC-VRPTW-ASYM-00c5356f-d1-n258-k12``:

<img width="1160" alt="Screen Shot 2023-02-12 at 15 11 46" src="https://user-images.githubusercontent.com/30997278/218316076-64d575d0-e776-45f4-ac5d-0f7bc45ad1a2.png">

- Local search takes about 2x longer than our last version in Euro NeurIPS. (The entire run with the pure C++ code took 17 seconds.) I don't have a logical explanation now that the population diversity management and penalties seem fixed. But I haven't profiled the C++ code to see what exactly happens.
- The current `Population.add` implementation is slow. @wouterkool proposed a solution [here](https://github.com/N-Wouda/PyVRP/pull/55#discussion_r1095586298).

**Comment by N-Wouda** [comment]
@leonlan yes, but I'm first finishing up a CLI for #69. That'll include a profile option so we can gather results from benchmark runs as well.

**Comment by N-Wouda** [comment]
I have cut some of this in #83 (@leonlan can you compare?), but it's just fundamentally Python underneath. We can probably cache some more calculations, but some of the Population methods just get called a lot - and that has overhead.

We should consider moving Population back to C++, if we care about this a lot.

@leonlan also note that 'our' LS has two more NODE_OPERATORS than the Euro/NeurIPS had. We haven't really settled on which operators to include by default, so I have included them all. That makes our LS a bit slower already (but you can easily comment out the Exchange3X range).

**Comment by leonlan** [comment]
I think if we really want to be pragmatic then we should go back to the C++ side for Population. It's much faster, and the [bug](https://github.com/N-Wouda/PyVRP/issues/44#issuecomment-1407356471) in `purge` is now identified (the diversity in proximity was stored in an integer variable, resulting in 0 diversity). Worst case, if this doesn't work, we can even go back to the EURO-NeurIPS version.

Also, I think there are currently some diversity issues in Population. The avg. diversity seems too high throughout the runs (~0.20) compared to 0.10-0.15 in Euro NeurIPS. That could partially explain why LS is slower, because the produced offspring require many more iterations.

**Comment by N-Wouda** [comment]
> Also, I think there are currently some diversity issues in Population. The avg. diversity seems too high throughout the runs (~0.20) compared to 0.10-0.15 in Euro NeurIPS. That could partially explain why LS is slower, because the produced offspring require many more iterations.

That's for the most part due to the changes I've made to the broken pairs distance measure to symmetrise it (but there could also be issues in the rest of the code).

**Comment by N-Wouda** [comment]
I'm running current main (e04aba4a0849a7c9579eac1e76d1283bf3e67170) on the GH1000 instances with runtime 1H each on our computer cluster. Will update here once results are in.

**Comment by wouterkool** [comment]
Can we separate performance issues into speed and functional differences? Is the code just slower or do we get worse results with the same number of iterations as well?
- I think 10 - 20% slower due to Python is acceptable, and most of the running time should be in the local search, but we should get the same results with same number of iterations
- Can't we keep the population at Python side but have a separate datastructure to compute the diversity which I think is the bottleneck? Basically it's an $n x n$ matrix where you want to add/remove rows quickly and query avg of top-k nearest or so.
- As an alternative, could we have something which approximates the diversity somehow, e.g. not updating every iteration (e.g. as if we would compute multiple offspring in parallel), I would not guess this makes a huge difference
- I think the params you used for EURO-NeurIPS instances are different than we used for DIMACS GH1000 instances, where we had growing neighbourhoods which helped significantly with the quality of the result, so maybe let's test with the same params and compare quality vs iterations and iterations vs time, as well as LS iterations per genetic algorithm iteration

**Comment by wouterkool** [comment]
So I propose to first focus on getting similar results with similar number of iterations (both genetic algorithm iterations and LS iterations), and then focus on optimizing the speed.

**Comment by N-Wouda** [comment]
I'm also benchmarking #83 right now (again 1H), and will add another run of 2H here later so we can more accurately compare against the DIMACS result.

**Comment by N-Wouda** [comment]
> See #85 there was a bug in the sorting in the population so the fitness was not computed correctly, so I'm not sure how representative these results are anymore.

Agree, I'll run another one.

**Comment by N-Wouda** [comment]
Currently running #83 (0795a0f32b6b7fb956b5466a7ea2d793bd6c30a9) for 1H with `nb_granular = 40`. It's already started, results should be in in 3H.

**Comment by N-Wouda** [comment]
This is 0fb21051ef0a091d770bab1c0e0fb2e0c7eb2542 on the `population-generics` branch:
```
      Avg. objective: 336667
     Avg. iterations: 82114
   Avg. run-time (s): 3600.03
        Total not OK: 0
```

**Comment by N-Wouda** [comment]
There are a few benchmark results in #91. That branch basically doubles performance.
