### ISSUE TITLE
Question about heterogeneous fleet

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#451]
Hello, I'm trying PyVRP to solve CVRP and CVRPTW problems and found that PyVRP works fine for solving these problems.
The program is well organized, tutorial and API documents are well prepared and they helped me to understand the program. 
Plotting is also fine. 
Thank you for sharing nice program!

Now I have an interest to apply PyVRP to solve real world problem which is the scheduling of trucks.
In this problem, there are several types of truck which have different capacity. 
They depart from a depot, collect luggage from clients, and return back to the depot.
So, I want to set different vehicle capacities in PyVRP.

In the README file, it says PyVRP supports heterogeneous feet VRP,

> PyVRP is an open-source, state-of-the-art vehicle routing problem (VRP) solver. It currently supports VRPs with:
> * Vehicles of different capacities, costs, and shift durations (heterogeneous fleet VRP);

Is this "heterogeneous fleet VRP" problem supported in the current stable version (v0.7.0) or development version?
Though I read API document, I could not find the way to set different capacity values to vehicles. 
I appreciate if you can tell me the way to set different vehicle capacity values.

I appreciate for your contribution to develop and share nice program. 
I'm looking forward to further development of this program. 
Thank you.

_Originally posted by @mstf2077 in https://github.com/PyVRP/PyVRP/issues/188#issuecomment-1923394815_

**Comment by N-Wouda** [comment]
Hi @msft2077! 👋 

Vehicles of different capacities are supported in the current stable version. Have a look at the [multi-depot example](https://pyvrp.org/examples/quick_tutorial.html#Multi-depot-VRP-with-time-windows) to see how to specify multiple vehicle types, and then use the [relevant API documentation](https://pyvrp.org/api/pyvrp.html#pyvrp._pyvrp.VehicleType) to find out how to specify vehicles of different capacities. It works something like this (for example):
```python
from pyvrp import Model

m = Model()
veh_type1 = m.add_vehicle_type(num_available=3, capacity=5)
veh_type2 = m.add_vehicle_type(num_available=5, capacity=15)
```
Which adds 3 vehicles of capacity 5, and 5 vehicles of capacity 15 to the model.

**Comment by mstf2077** [comment]
Hi, @N-Wouda !
Thank you for your quick response. I really appreciate for your help.
I will try that way. I will read the multi-depot example again. I was sorry that I did not have enough understanding of the program.
Thank you!

**Comment by N-Wouda** [comment]
@mstf2077 no worries! I'm glad we got this resolved 🎉. If you have another question, feel free to open another issue in the future!

**Comment by mstf2077** [comment]
@N-Wouda Thank you! With your appropriate advice, I could get expected results! Wonderful! 😄 
Thank you so much! I will try further scenarios. Have happy coding! 👍

**Comment by N-Wouda** [comment]
@mstf2077 great to hear, and good luck with your tasks!

If there's anything PyVRP does not yet do that you think would be a valuable addition, please let us know. We're very interested in learning how PyVRP is used!
