### ISSUE TITLE
Multiple load dimensions

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#458]
#### Is your feature request related to a problem? Please describe

Right now we consider a single capacity constraint, which might resemble weight. We should probably be able to (simultaneously) support constraints on the following:
- Size (width, height, depth)
- Weight (kg, litre)
- \# items (bags, packages, boxes)

Size restrictions can quickly turn into a bin packing problem, which is pretty hard (see some of the references below). I do not think we need to add support for bin packing via this issue.

#### Describe the solution you'd like

Some support for additional loading constraints.

#### Describe alternatives you have considered

N/A

#### Additional context

Came up in a conversation I had today and is something we discussed before, I think. I'm writing this out here so I do not forget about it.

**Comment by N-Wouda** [comment]
Maybe this should more generally be "rethink capacity constraints", because we might want to make a clearer separation between _weight_/_load_ constraints on the one hand, and _volume_/_space_ use on the other.

**Comment by N-Wouda** [comment]
I recall that something similar to this came up in the [ROADEF 2022 challenge](https://www.roadef.org/challenge/2022/en/index.php). Might be relevant.

**Comment by leonlan** [comment]
Two relevant surveys to help determine the scope:

> Ostermeier, M., Henke, T., Hübner, A., & Wäscher, G. (2021). Multi-compartment vehicle routing problems: State-of-the-art, modeling framework and future directions. European Journal of Operational Research, 292(3), 799–817. https://doi.org/10.1016/j.ejor.2020.11.009

> Gu, W., Archetti, C., Cattaruzza, D., Ogier, M., Semet, F., & Speranza, M. G. (2023). Vehicle routing problems with multiple commodities: A survey. European Journal of Operational Research. https://doi.org/10.1016/j.ejor.2023.11.032

**Comment by N-Wouda** [comment]
Thanks! I recall having skimmed the 2023 survey paper a few months ago. I'll have another look soon.

**Comment by N-Wouda** [comment]
I would like to have a weight and volume split in the codebase soon, along with a simple `Parcel`-like object to store that data. I might work on that after #471. Beyond weight/volume I do not need much more complicated packing constraints for now.

**Comment by N-Wouda** [comment]
@wouterkool proposed a few weeks ago to treat 'load' more generally, as say multiple dimensions of stuff picked up or delivered at a customer. The question is how to make this work nicely. Do we want to allow for arbitrary dimensions, or limit the number? Should they have names?

**Comment by N-Wouda** [comment]
I still don't really know how to do multiple/arbitrary user-specified dimensions in a nice way. Let's first think of an interface of sorts before we go into the algorithmics.

**Comment by N-Wouda** [comment]
VROOM keeps it simple, and assumes an arbitrary array is passed of (multiple) quantities. See [their docs](https://github.com/VROOM-Project/vroom/blob/release/1.14/docs/API.md) for more details. I suppose we could start there for our implementation as well. The `ProblemData` instance can then check whether all arrays are of the same length.

**Comment by N-Wouda** [comment]
Esri does the same thing as VROOM: they have a `Capacities` field on the vehicles that's just an array of quantities (see [here](https://developers.arcgis.com/rest/routing/vehicle-routing-problem-service/#routes)).

I'm pretty much convinced by now that we should do the same. I'd have liked to also have labels for these different quantities (so we know what's at each index), but that's not really required and seems difficult to make this work nicely.

Imlementation-wise, I guess we'd duplicate the `LoadSegment` and associated penalty value for each load dimension?

**Comment by N-Wouda** [comment]
For the interface I am defaulting to empty lists if the user doesn't pass anything. I think that's reasonable. But what do we do if the user only sometimes passes data? E.g., `delivery=[1, 2, 3]` for one client, but nothing for another (so it defaults to `delivery=[]`)? Should we allow that? Or explicitly require that the user passes the same amount of dimensions in every case, if they use the feature? We should probably not require users to pass both pickup _and_ delivery, if they use only one of the two.

**Comment by N-Wouda** [comment]
> E.g., `delivery=[1, 2, 3]` for one client, but nothing for another (so it defaults to `delivery=[]`)? Should we allow that?

Probably not because it makes validation harder.

**Comment by N-Wouda** [comment]
A question remains whether we should have a single load penalty, or one penalty per load dimension (and similarly, feasibility checks per load dimension). We default to a single load penalty in #645 for now.
