### ISSUE TITLE
SearchMethod protocol

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#46]
We currently have one search method, the `LocalSearch` class. If we are to support additional methods, we should standardise an interface for such methods that e.g. `GeneticAlgorithm` can rely on. This issue exists to determine that interface.

**Comment by leonlan** [comment]
> Slightly off-topic: In view of our long-term ambition to possibly include algorithms other than HGS, to what extent should be keep the docs (and code structure) specific to HGS? E.g., `educate` is a HGS-specific term, and it would probably be more future proof to rename this to `local_search`.
>  ...
> _Originally posted by @leonlan in https://github.com/N-Wouda/PyVRP/pull/75#discussion_r1101053697_


>  I've given this some thought, and settled on educate because it'd also cover non-LS type of educators. I'm not entirely sure what we want to do, but we probably do want to facilitate people hybridizing with, say, ALNS (I recall a paper doing HGS + ALNS) or something else.
> 
> This also ties into #46, which might have LS derive from a base Educator class to express this intent more clearly. A discussion about this can probably take place there.
> 
> _Originally posted by @N-Wouda in https://github.com/N-Wouda/PyVRP/pull/75#discussion_r1101131530_

**Comment by N-Wouda** [comment]
I suggest we call it `SearchMethod`, rather than `Educator`. We should think of an overall `SearchMethod` protocol that e.g. `GeneticAlgorithm` can rely on. In that sense, #122 duplicates this issue somewhat.

**Comment by N-Wouda** [comment]
I think we can keep this pretty simple, and only impose something like this:
```python
class SearchMethod(Protocol):

  def __call__(self, sol: Solution) -> Solution:
    pass

  def on_best(self, best: Solution) -> Solution:
    pass
```
The `on_best` thing is something we'll need if we want to replicate our current GA exactly. We might eventually want to do that differently so we can simplify this further. My ideal target is a search method that also allows a simple function, that is, only requires `__call__`.

**Comment by leonlan** [comment]
`on_best` was removed in https://github.com/PyVRP/PyVRP/pull/287.

**Comment by N-Wouda** [comment]
Yeah you're right! I still had the old situation in my head. Great, then just a function it is!

**Comment by wouterkool** [comment]
I just wonder, currently the Python local search has `run`, `search` and `intensify`. All three of them are functions accepting a `solution` and `costEvaluator` and therefore all three of them implement this protocol, which I think is correct as all three of them can be seen as search methods. Rather than passing the `LocalSearch` objects we can pass the individual functions, binding the local search object as argument. Is that correct?

The user then has the freedom to implement his own function as well, either as normal function, class function or a class with explicit `__call__` implementation, do you see it like that as well?

**Comment by N-Wouda** [comment]
> I just wonder, currently the Python local search has `run`, `search` and `intensify`. All three of them are functions accepting a `solution` and `costEvaluator` and therefore all three of them implement this protocol, which I think is correct as all three of them can be seen as search methods. Rather than passing the `LocalSearch` objects we can pass the individual functions, binding the local search object as argument. Is that correct?

Yes, that works under #297. I see most of this as a bit of a historical coincidence due to how we implement `LocalSearch.__call__`.

> The user then has the freedom to implement his own function as well, either as normal function, class function or a class with explicit `__call__` implementation, do you see it like that as well?

Yes.
