### ISSUE TITLE
Vehicle-dependent distances and durations

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#475]
#### Is your feature request related to a problem? Please describe

Right now PyVRP assumes there is a single distance and duration matrix that applies to all vehicle types. This is unrealistic for heterogeneous fleets.

#### Describe the solution you'd like

A way to set different distances and durations for different vehicle types.

#### Additional context

Brought up in #441 by @Stanpol.

**Comment by N-Wouda** [comment]
A big open question here is interface. I think the following could work:
```python
m = Model()
veh_type1 = m.add_vehicle_type()

m.add_edge(..., vehicle_type=None)  # default, applies to all vehicle types
m.add_edge(..., vehicle_type=veh_type1)  # overrides default - only applies to veh_type1
```
Additionally, we'll need to look into how to make this fast. Maybe find a little literature?

**Comment by N-Wouda** [comment]
I'm tentatively assigning this to the milestone for release v0.10.0, with the understanding that I am not very good at planning two releases ahead :-).

**Comment by N-Wouda** [comment]
To do this we may want to remove/deprecate `pyvrp::ProblemData::dist` and `pyvrp::ProblemData::duration`, and instead require access via `pyvrp::ProblemData::distanceMatrix` (and `durationMatrix`). That way we can parameterise the matrix accessors with a `size_t vehicleType` argument to return the correct matrix. [Later, if and when we also want to allow time-dependent VRP, we can add another argument to indicate the time.]

**Comment by N-Wouda** [comment]
This should also get us #329: for vehicle types not allowed to visits certain locations, simply set all arcs to those locations to a very high cost. That should guarantee those locations are not visited by those vehicle types.

**Comment by N-Wouda** [comment]
> Additionally, we'll need to look into how to make this fast.

I'm thinking of somehow tagging the underlying matrices somehow. If vehicles use the same matrix, we can use the cached data on `pyvrp::search::Route` when evaluating moves. Only when they don't we would need to recompute. This can be as simple as storing a distance/duration matrix index on the `VehicleType`, which can be used to as the `ProblemData` instance for the actual matrix. If the indices are the same on two different vehicle types we can just reuse the cached data; else we recompute.

**Comment by N-Wouda** [comment]
Moving this up to 0.9.0.

**Comment by leonlan** [comment]
Moidfied X instances for HVFRP (with heterogeneous costs and distances) can be found in 
> Pessoa, A., Sadykov, R., & Uchoa, E. (2018). Enhanced Branch-Cut-and-Price algorithm for heterogeneous fleet vehicle routing problems. European Journal of Operational Research, 270(2), 530–543. https://doi.org/10.1016/j.ejor.2018.04.009

**Comment by N-Wouda** [comment]
This might be pretty easy algorithmically if we go in the direction of #534: the `Route::Proposal` class knows which route it belongs to, as do the segments/proxy objects. If the proposed route's matrix is different from that used for any of the segments, we recompute with the new matrix; else we return the cached data.

Supporting this nicely in terms of interface/data access is a lot harder.

**Comment by N-Wouda** [comment]
I want to figure out if we can somehow 'tag' each matrix, so that we can add a matrix tag/idx attribute to the vehicle types (or store such a tag somewhere else, but at least in a way that we can quickly get from vehicle/tag -> actual matrix). I think such things are called profiles - see OSRM [for example](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md). We can then track in each proxy segment for which profile the segment is valid, and if it is invalid, recompute the data (by obtaining the actual matrix based off the vehicle's profile tag).

Something like
```cpp
struct VehicleType
{
  ...
  size_t profile;
};
```
and
```cpp
class ProblemData
{
  Matrix<Distance> const &distanceMatrix(size_t profile) const;
  Matrix<Distance> const &durationMatrix(size_t profile) const;
};
```
seem like a logical way to structure the data for this.

**Comment by N-Wouda** [comment]
From what I've gathered there's quite a bit of demand for this, so it's good we're tackling this next :-).

**Comment by N-Wouda** [comment]
#573 brought routing profiles to PyVRP, but we do not yet use those in the move evaluations in the local search. That's part of the next PR.
