### ISSUE TITLE
Strange population management behavior on VRPSPD instances

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#482]
#### Is your feature request related to a problem? Please describe
I created benchmark instances for VRP with simultaneous pickup and delivery (VRPSPD). A few instances, specifically type 1 instances with 400 clients, had a relatively high gap, so I tried investigating the solver behavior in more detail.

##### Reproduction steps:
1. I made instances for VRPSPD here: [VRPSPD.zip](https://github.com/PyVRP/PyVRP/files/14361907/VRPSPD.zip)
2. I modified `read.py` here to support VRPSPD instances: https://github.com/PyVRP/PyVRP/compare/main...vrpspd
3. Build in double precision mode: ```poetry run python build_extensions.py --precision double --clean```

4. Then I modified `cli.py` to plot stats figures and ran the following command:
``` sh
poetry run pyvrp VRPSPD/VRPSPD/*1_4_*.vrp --max_runtime 300 --seed 0 --num_procs 3 --stats_dir tmp/vrpspd
```

This results in one figure per instance as shown below:

<details>
<summary>C1_4_1</summary>

![C1_4_1](https://github.com/PyVRP/PyVRP/assets/30997278/0f53b086-ebb8-4f34-8dc6-08293a6e193b)

</details>

<details>
<summary>R1_4_1</summary>

![R1_4_1](https://github.com/PyVRP/PyVRP/assets/30997278/b72ce6ca-d4db-42b6-864f-c6bee050d9f9)

</details>

<details>
<summary>RC1_4_1</summary>

![RC1_4_1](https://github.com/PyVRP/PyVRP/assets/30997278/ac39c129-4cbd-4e22-a719-2dcc7f5435b0)

</details>

#### Describe alternatives you have considered
A clear and concise description of any alternative solutions or features you have considered.

#### Additional context
Add any other context about the feature request here.

**Comment by N-Wouda** [comment]
![image](https://github.com/PyVRP/PyVRP/assets/16272507/b343d83a-a9fb-45a9-ba2a-0f918b5cbd34)

OK, so, the diversity remains really high throughout the search. Why? And does it even converge? Not much is happening if I look at the objective values in the above figure.

**Comment by N-Wouda** [comment]
We should triage to see if this is a bug, a configuration issue, or perhaps even something in the data. I'm not sure.

**Comment by leonlan** [comment]
Three points that are noteworthy and worth investigating further:
- The diversity is very high
- The feasible average costs is very high
- The infeasible best has significant jumps

**Comment by leonlan** [comment]
OK, I think that the large jumps might be related to capacity penalties that jump. This is related #198. We should definitely track penalties separately.

**Comment by N-Wouda** [comment]
I don't think we have a priority label or some such, but this one is pretty important to figure out before we cut a new release to PyPI. I at least want to understand what's going on before we ship v0.8.0 with support for VRPSPD.

**Comment by leonlan** [comment]
Tackling this one next...

**Comment by leonlan** [comment]
So I don't think the problems that I raised in this issue are bugs.
- **High feasible average**: this is due to a single initial random solution sticking around for a long time. It's not getting purged because it has very high diversity, so it manages to survive for a long time. This behavior can also be observed in CVRP instances.
- **High diversity**: I think this is a result of the solutions converging very slowly. I don't think it's bugged.
- **Jumps in infeas best cost**: The load violations can be very big, so whenever the penalty jumps from 1 to 2, this creates a spike in the infeasible costs, which are plotted with the actual penalty value during that iteration. 

I ran a benchmark again on the VRPSPD instances:

| name    |   ('gap', 'mean') |   ('gap', 'min') |   ('gap', 'max') |
|:--------|------------------:|-----------------:|-----------------:|
| C101    |              0.06 |             0    |             0.07 |
| C1_2_1  |              0.52 |             0.23 |             0.84 |
| C1_4_1  |              1.12 |             0.66 |             1.59 |
| C201    |              0    |             0    |             0    |
| C2_2_1  |              0.01 |             0    |             0.07 |
| C2_4_1  |              0.3  |             0.09 |             0.49 |
| R101    |              0    |             0    |             0    |
| R1_2_1  |              0.11 |             0.05 |             0.26 |
| R1_4_1  |              1.68 |             1.32 |             2.17 |
| R201    |              0    |             0    |             0.02 |
| R2_2_1  |              0.14 |             0    |             0.72 |
| R2_4_1  |              0.55 |             0.32 |             0.94 |
| RC101   |              0.01 |             0    |             0.05 |
| RC1_2_1 |              0.32 |             0.01 |             0.94 |
| RC1_4_1 |              1.64 |             1    |             2.44 |
| RC201   |              0.04 |             0    |             0.19 |
| RC2_2_1 |              0.05 |             0    |             0.51 |
| RC2_4_1 |              0.1  |             0.01 |             0.18 |

They're better than last time (which had 2-3% gaps). I don't know why that improved. The results still don't get close to UHGS (~0.5% gap) on the 400 client instances of category 1, but I can live with it. It could be some parameter setting, or the lack of node coordinates in the instances, or something else. 

Since we're not benchmarking on these instances anyway, I don't see any reason to improve PyVRP's performance on these any further. Closing this issue.

**Comment by leonlan** [comment]
Adding node coordinates improved performance on the category 1 instances, but decreased performance on category 2 instances. Overall, the gap decreased from 0.37% to 0.27% so that's overall an improvement.

| name    |   ('gap', 'mean') |   ('gap', 'min') |   ('gap', 'max') |
|:--------|------------------:|-----------------:|-----------------:|
| C101    |              0.07 |             0.07 |             0.07 |
| C1_2_1  |              0.23 |             0.05 |             0.31 |
| C1_4_1  |              0.59 |             0.38 |             0.84 |
| C201    |              0    |             0    |             0    |
| C2_2_1  |              0.09 |             0    |             0.41 |
| C2_4_1  |              0.55 |             0.19 |             1.18 |
| R101    |              0.14 |             0    |             0.68 |
| R1_2_1  |              0.19 |             0.04 |             0.55 |
| R1_4_1  |              0.26 |             0.03 |             0.53 |
| R201    |              0.09 |             0    |             0.34 |
| R2_2_1  |              0.5  |             0    |             1.73 |
| R2_4_1  |              0.91 |             0.31 |             1.29 |
| RC101   |              0.11 |             0    |             0.18 |
| RC1_2_1 |              0.33 |             0    |             0.66 |
| RC1_4_1 |              0.13 |             0.01 |             0.36 |
| RC201   |              0.08 |             0    |             0.59 |
| RC2_2_1 |              0.17 |             0    |             0.79 |
| RC2_4_1 |              0.6  |             0.31 |             1.07 |

**Comment by N-Wouda** [comment]
Looks good! The minimum gaps are all very nice (BKS or near BKS most of the time), but there is clearly still quite a bit of variability in the search. What's the stopping criterion here?
