### ISSUE TITLE
Fix RTD with latest Poetry

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#488]
Read the docs is broken; see e.g. [here](https://readthedocs.org/projects/pyvrp/builds/23554985/) for failing output. This could have to do with the new Poetry release from earlier today. In any case, it needs to be investigated and ideally be fixed if we can do so.

**Comment by N-Wouda** [comment]
[This output](https://readthedocs.org/projects/pyvrp/builds/23555062/) suggests `poetry` is not installing its dependencies into the same environment `pip` looks at. That's a change from previous versions of poetry/RTD which explicitly recommend setting things up in the way we have it now.

**Comment by N-Wouda** [comment]
The previous version of Poetry (1.7.1, as opposed to 1.8.0 which released this morning) does not have this problem: [this build](https://readthedocs.org/projects/pyvrp/builds/23555112/) works fine. So this is definitely related to the recent Poetry release. 

For now I'll pin `poetry==1.7.1` as a temporary fix in #489, and keep this issue open to revisit this once RTD fixes the issue. We are not likely to be the only ones running into this.

**Comment by N-Wouda** [comment]
Issue tracked in https://github.com/readthedocs/readthedocs.org/issues/11150.

**Comment by ewjoachim** [comment]
[Here](https://github.com/readthedocs/readthedocs.org/issues/11150#issuecomment-1963074192)'s a workaround :)

**Comment by N-Wouda** [comment]
Fantastic, thank you @ewjoachim!
