### ISSUE TITLE
Should we keep double precision?

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#491]
With 64-bit integers we can support very large integer values. That calls into question whether the continued support for double-precision computations is still worth it. It adds complexity to the implementation through a feature flag, and doubles our CI requirements because we test everything both in double and integer precision mode.

**Comment by N-Wouda** [comment]
I am leaning no, but we should probably test if we can do without by running e.g. the MDVRPTW benchmark instances in integer precision. Those did not used to work before, but with int64 and some scaling they likely will be fine now.

**Comment by leonlan** [comment]
I'm also in favor of removing this. 

> We might want to add an "exact" round func to read() that defaults to what the EXACT_2D specification in VRPLIB does: multiply everything by 1000, and round down to the nearest integer.

We can also just change this in the VRPLIB format and let `vrplib` handle this (Together with other rounding covnentions such as DIMACS).

**Comment by N-Wouda** [comment]
@leonlan do you know if we can remove this? Basically I'm asking if int precision now works for MDVRPTW or not.

**Comment by leonlan** [comment]
Haven't checked this yet. I assigned it to myself for next week.

**Comment by N-Wouda** [comment]
> @N-Wouda Will you remove double precision mode? I'm not so familiar with the `Measure` type :-)

Sure but this is also a great learning opportunity 😄
