### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#5]
A list of things we might want to add.

I'll start:
- Non-homogeneous vehicle capacities. This should not be too hard to build into the algorithm. 
- Waittime in objective.

**Comment by N-Wouda** [comment]
> * Multiple depots

This is something I'd like as well. I don't think it'll be too hard to support either.

**Comment by leonlan** [comment]
Not an easy extension, but many variants can be reduced to an instance of the pickup-and-delivery problem with time windows, see https://www.sciencedirect.com/science/article/pii/S0305054805003023.

**Comment by N-Wouda** [comment]
> Not an easy extension, but many variants can be reduced to an instance of the pickup-and-delivery problem with time windows, see [Pisinger and Ropke (2007)](https://www.sciencedirect.com/science/article/pii/S0305054805003023).

I've been thinking about pickups (we obviously already do delivery). That'd require quite a few changes here and there, but it might not be too hard. It is something I'd like to add at some point.

**Comment by N-Wouda** [comment]
I'm not really sure which issue is appropriate for this, but [this repo](https://github.com/Valdecy/pyVRP) implements another genetic algorithm that supports a bunch of extensions we're also considering (multiple depots, heterogeneous fleet). The implementation or just interface might be of some use to us.

**Comment by N-Wouda** [comment]
I'm closing this issue. Of the remaining open extensions mentioned here:
- Multiple depots is tracked in #305;
- Max dist/dur in #330;
- Pickup and delivery in #331.
