### ISSUE TITLE
Removing unnecessary local search operators

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#501]
We briefly discussed in #94 whether we should remove MoveTwoClientsReversed or not, but we need data to support this decision. This issue investigates this further in a more general setting: which local search operators can we remove without affecting PyVRP's performance? The simpler we can make PyVRP, the better!

**Comment by leonlan** [comment]
I ran a benchmark on main, with the default config and two variants:

1. Variant 1: benchmark configs with LS ops:
	- Exchange-(1, 0)
	- Exchange-(1, 1)
	- TwoOpt
	- SwapStar
2. Variant 2: benchmark configs with:
	- Exchange-(1, 0)
	- Exchange-(1, 1)
	- Exchange-(2, 0)
	- Exchange-(2, 1)
	- Exchange-(2, 2)
	- TwoOpt
	- SwapStar


These are the results:
|         | Default | Variant 1 | Variant 2 |
|---------|---------|----------|----------|
| CVRP    | 0.24%   | 0.24%    | 0.23%    |
| VRPTW   | 0.58%   | 0.63%    | 0.56%    |
| VRPB    | 0.29%   | 0.39%    | 0.30%    |
| PCVRPTW | 0.35%   | 0.40%    | 0.37%    |
| MDVRPTW | 0.66%   | 0.97%    | 0.75%    |


- Differences on MDVRPTW is due to the NoImprovement stopping criterion which is set at 2.5K iters. This is somewhat unfair for the new variants, which have way more iterations per second, so they terminate much earlier (on average 960s vs. 420s vs. 590s. for the variants above).
- Variant 1 is slightly worse, but it works surprisingly well with how little operators are included.
- Variant 2 is almost as good as default except for MDVRPTW due to the explanation above.
- I also added RelocateStar to variant 1, but those results were sometimes worse, which means that RelocateStar is not really effective. SwapStar is effective because it explores a neighborhood that is not covered by any of the other node operators.

**Comment by leonlan** [comment]
Based on these results, I propose the following:
- [ ] Completely remove MoveTwoClientsReversed.
- [ ] Completely remove RelocateStar.
- [ ] Remove Exchange-(3, *) variants from configs.
- [ ] (?) We could also remove SwapRoutes completely, but I don't know for sure since we only have one heterogeneous fleet benchmark. We can wait with this one until we have more HF benchmarks.

**Comment by N-Wouda** [comment]
> * [ ]  Completely remove MoveTwoClientsReversed.
> * [ ]  Completely remove RelocateStar.
> * [ ]  Remove Exchange-(3, *) variants from configs.

Agree

> * Keep only `cvrp.toml` and `vrptw.toml` (use `vrptw.toml` for MDVRPTW).

Can we hold off on this until such a time where we know what we want to do about the default parameters? This feels like an in-between solution to just tuning over all the instances, and keeping the best configuration setting as the default arguments in PyVRP (rather than benchmark set-specific config files).

> * (?) We could also remove SwapRoutes completely, but I don't know for sure since we only have one heterogeneous fleet benchmark. We can wait with this one until we have more HF benchmarks.

I can imagine this matters more when vehicles are much more differentiated than they are now. We should probably be a bit cautious here, so I think waiting until we support more of these kinds of benchmarks to gather further evidence is a good idea.

**Comment by leonlan** [comment]
> Can we hold off on this until we know what we want to do about the default parameters? This feels like an in-between solution to just tuning over all the instances, and keeping the best configuration setting as the default arguments in PyVRP (rather than benchmark set-specific config files).

Sure thing. I opened a related issue #505.

**Comment by N-Wouda** [comment]
In line of #504, should we also investigate SwapTails/ReverseSegment separately? I'm convinced of SwapTails, but ReverseSegment (the OG 2-OPT) not so much. Perhaps a quick run on the CVRP set (where reversing isn't a terrible idea) can show its value? If it's valuable we'll obviously keep it, but I have no good intuition about ReverseSegment.

**Comment by leonlan** [comment]
Yeah I can run #510: with everything, without SwapTails, and without ReverseSegment.

**Comment by leonlan** [comment]
Here are the results:

|                   | default (all ops) | no reverse segment | no swap tails |
|-------------------|-------------------|-------------------|---------------|
| Gap | 0.25%             | 0.24%             | 0.27%         |

The effects of reverse segment are anyhow very limited because it only runs on intra-route node combinations, and these interactions are already fairly limited because we have granular neighborhoods.

Not sure what conclusion to draw from this. We can run more experiments, or just remove/keep it. I don't have a strong opinion on this.

**Comment by N-Wouda** [comment]
> Not sure what conclusion to draw from this. We can run more experiments, or just remove/keep it. I don't have a strong opinion on this.

I'm leaning remove because:
- This operator is annoying to maintain because reversing is not something we do anywhere else, so there's a lot of stuff that has to be special-cased here just to support this move;
- It's not clear if this operator is adding value even for CVRP, where tours can be reversed without easily incurring additional infeasibilies. For completeness we could also consider testing the VRPTW instances (or any other instance with directed routes) to see if `ReverseSegment` has added value there, but I kind of doubt it.

**Comment by leonlan** [comment]
Running VRPTW benchmark now. Let's finish this issue based on those results!

**Comment by leonlan** [comment]
OK, so it's pretty clear that SwapTails is very important and ReverseSegment is not (on VRPTW):

| category              | default (all ops) | no reverse segment | no swap tails |
|-------------------|-------------------|-------------------|---------------|
| C1       | 0.39      | 0.41      | 0.44      |
| C2       | 0.09      | 0.09      | 0.17      |
| R1       | 1.09      | 1.13      | 1.19      |
| R2       | 0.86      | 0.91      | 1.97      |
| RC1      | 1.13      | 1.13      | 1.22      |
| RC2      | 0.73      | 0.67      | 1.79      |
| Gap | 0.71%             | 0.72%             | 1.13%         |


I'll remove ReverseSegment as well in #511.
