### ISSUE TITLE
Solve ignores max run time when setting fixed_cost parameter in add_vehicle_type in multi depot szenario

### ISSUE THREAD

**Issue by camold** [PyVRP/PyVRP#507]
#### Describe the bug

First of all, thank you very much for all the work that went into PyVRP. Highly appreciated.
I'm trying to make my way into solving a problem that is related to locomotive scheduling in cargo transportation. This is a multi-depot problem and one of the goals is to also have as few locomotives as possible. So I figured, the `fixed_costs` parameter could be handy.

However, using this parameter with a small example fails - the runtime restriction is ignored and the computation never comes back to live (it runs at 100% CPU but never returns).

#### Code sample

```python
from pyvrp import Model
from pyvrp.stop import MaxRuntime

COORDS = [
    (456, 320),  # first depot
    (228, 0),  # second depot
    (912, 0),
    (0, 80),
    (114, 80),
    (570, 160),
    (798, 160),
    (342, 240),
    (684, 240),
    (570, 400),
    (912, 400),
    (114, 480),
    (228, 480),
    (342, 560),
    (684, 560),
    (0, 640),
    (798, 640),
]

m = Model()
depots = [m.add_depot(x=COORDS[idx][0], y=COORDS[idx][1]) for idx in range(2)]

for depot in depots:
    m.add_vehicle_type(3, depot=depot, fixed_cost=1000)

clients = [
    m.add_client(x=COORDS[idx][0], y=COORDS[idx][1])
    for idx in range(1, len(COORDS))
]

locations = [depot, *clients]
for frm in locations:
    for to in locations:
        distance = abs(frm.x - to.x) + abs(frm.y - to.y)  # Manhattan
        m.add_edge(frm, to, distance=distance)

res = m.solve(stop=MaxRuntime(5))

```

<details>
pyvrp 0.7.0
python 3.10.7
Linux (Ubuntu)
</details>

**Comment by N-Wouda** [comment]
Hi @camold! 👋 

This issue is likely here:
> ```python
> locations = [depot, *clients]
> ```
You are not adding all arcs to the model, since `locations` includes only the last depot, not all of them. This should very likely be
```python
locations = [*depots, *clients]
```
The problem you are running into here likely has to do with integer overflow - when some arcs are not set, PyVRP by default uses a large numerical constant to set the distance and duration for that arc. This was not always numerically stable, but will be fixed when we release v0.8.0 in a few weeks!

**Comment by N-Wouda** [comment]
(note to self: update the docs to use `locations = depots + clients`, rather than unpacking.)

**Comment by camold** [comment]
Thanks for spotting the problem. This does the trick for the `fixed_cost` parameter.
Highly appreciated!
