### ISSUE TITLE
max_duration (of vehicles) is ignored in multi depot scenario

### ISSUE THREAD

**Issue by camold** [PyVRP/PyVRP#508]
#### Describe the bug

First of all, thank you for all the work that goes into PyVRP. Highly appreciated.
I'm trying to work my way into modelling a locomotive scheduling problem as VRP with PyVRP. This is a multi-depot problem where the vehicles (=locomotives) have some maximum duration they are allowed to drive. However, I get very weird solutions...

#### Code sample

```python
from pyvrp import Model
from pyvrp.plotting import plot_solution
from pyvrp.stop import MaxRuntime

COORDS = [
    (456, 320), # first depot
    (228, 0),  # second depot
    (912, 0),
    (0, 80),
    (114, 80),
    (570, 160),
    (798, 160),
    (342, 240),
    (684, 240),
    (570, 400),
    (912, 400),
    (114, 480),
    (228, 480),
    (342, 560),
    (684, 560),
    (0, 640),
    (798, 640),
]

m = Model()
depots = [m.add_depot(x=COORDS[idx][0], y=COORDS[idx][1]) for idx in range(2)]

for depot in depots:
    m.add_vehicle_type(2, depot=depot, max_duration=2000)

clients = [
    m.add_client(x=COORDS[idx][0], y=COORDS[idx][1], service_duration=500)
    for idx in range(2, len(COORDS))
]

locations = [depot, *clients]
for frm in locations:
    for to in locations:
        distance = abs(frm.x - to.x) + abs(frm.y - to.y)  # Manhattan
        m.add_edge(frm, to, distance=distance, duration=(distance/10))

res = m.solve(stop=MaxRuntime(5))
print(res)
plot_solution(res.best, m.data())

```

By setting the service duration to 500 this means each tour can maximally serve 4 (=2000/500) or rather 3 clients. However, I obtain lots of tours with five or more clients.
Note: the single depot case works better - all the tours have length at most 3 clients.

<details>

pyvrp 0.7.0
python 3.10.2
Linux (Ubuntu)

</details>

**Comment by N-Wouda** [comment]
> ```python
> locations = [depot, *clients]
> ```

This is definitely wrong - see your previous issue in #507.

**Comment by camold** [comment]
This solves the problem of infeasible routes.

However, I still get an `objective: INFEASIBLE`.
One may argue, that 2*2 vehicles is not enough, but even if I increase this to 2*10 I obtain a solution with infeasible objective where each tour is serving one client (hence 15 tours). And each of them should be feasible:

```python
[route.duration() for route in res.best.get_routes()]
# [600, 554, 560, 592, 606, 638, 654, 616, 654, 570, 648, 742, 570, 596, 646]
````

Setting `tw_early=0` and `tw_late=2000` then returns a different solution, again with (6) timewise feasible routes and an objective value.

Maybe it is advisable to add some assertion statements about missing parameters or wrong parameter configurations to avoid that the users are shooting their own feet ;-)
Thanks for the help!

**Comment by N-Wouda** [comment]
> Setting `tw_early=0` and `tw_late=2000` then returns a different solution, again with (6) timewise feasible routes and an objective value.

Yes, the defaults for both these parameters used to be `0`. The default for `tw_late` has been raised to `MAX_INT` in `main` due to #461, and will also be part of v0.8.0 in a few weeks.
