### ISSUE TITLE
Heuristic for SREX subproblem

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#521]
#### Is your feature request related to a problem? Please describe
In #482, we identified that PyVRP performs worse on instances without node coordinates. One of the reasons is that SREX relies on node coordinates to select routes for crossover. Without node coordinates, the selection problem is solved somewhat randomly, resulting in bad offspring.

#### Describe the solution you'd like
To become less dependent on these node coordinates, we should solve the SREX subproblem as an assignment problem. This is also described in the original work by [Nagata and Kobayashi (2010)](https://link.springer.com/chapter/10.1007/978-3-642-15844-5_54). See Section 3.2 and the Appendix.

- [ ] If we get rid of coords in SREX, we might want to check if we can set default coords to zero without hurting performance. Route overlap still relies on it but that may not be as important as SREX.

**Comment by N-Wouda** [comment]
> One of the reasons is that SREX relies on node coordinates to select routes for crossover.

The way this now works is that SREX sorts by route angle, which is computed as the angle of the route's centroid to the centroid of all clients in the instance. Such centroids are based on the node coordinates in the instance.

Relevant code:

https://github.com/PyVRP/PyVRP/blob/806a802f5970cd28e1287e2bce9d00fc504b633b/pyvrp/cpp/crossover/selective_route_exchange.cpp#L16-L31

**Comment by N-Wouda** [comment]
The arguments here:
```
     auto cmp = [&data](Route a, Route b) {
         return routeAngle(data, a) < routeAngle(data, b);
     };
```
should probably be `Route const &a, Route const &b`? This is needless copying.

**Comment by leonlan** [comment]
Two alternative SREX heuristics:
- [Blocho and Nalepa (2017](https://link.springer.com/chapter/10.1007/978-3-319-55453-2_9): Least Common Subsequence-based SREX
- [Cybula et al. (2021)](https://doi.org/10.1145/3449726.3459574): Maximum coverage problem

**Comment by N-Wouda** [comment]
If we do crossover better we have much less work in the LS. That means more iterations/more locally optimal solutions. And maybe better performance? In any case making a bit of a study out of this could be well worth doing, since it should not be too hard to improve over the route angle heuristic we use now.

**Comment by N-Wouda** [comment]
Something to investigate:
- Is a basic greedy algorithm for the maximum coverage problem already better than what we have now? 
- Are there relatively simple, fast constructive heuristics for the maximum coverage problem?

**Comment by N-Wouda** [comment]
This short and simple paper [here](https://luizsatoru.github.io/conteudo/artigos/ALIO-EURO2008-Luciana.pdf) might also be relevant for us. It's essentially a greedy constructive algorithm with a simple (local) search strategy on top for a few iterations. Might be really fast, and from their results seems to be really good for a closely related problem.

**Comment by N-Wouda** [comment]
I did some simple instrumentation to get a better feeling for what's going on. I took two large VRPTW and CVRP instances, each with 1000 clients. Then I ran each instance for 1000 iterations, and in each iteration tracked regular statistics (incl. runtime) and the number of missing clients in the offspring solution returned by SREX.

### VRPTW

The number of missing (unplanned) clients steadily goes down and settles at around 2% on the instance I solved. This shows clear convergence to an acceptable level of unplanned clients:

<img width="480" alt="image" src="https://github.com/PyVRP/PyVRP/assets/16272507/a69c55e8-afde-4e42-9ae9-adfb9b14e7f2">

The runtimes per iteration are not too big, so this is a 'nice' instance that we manage to solve well.

### CVRP

Here our polar angle heuristic seems to fail us, there is no clear convergence towards a small number of unplanned clients: the average is about 5% of the instance size, with many erratic peaks to hundreds of clients even half a minute into the search:

<img width="489" alt="image" src="https://github.com/PyVRP/PyVRP/assets/16272507/ffbdc6b9-49a0-4b51-ab0c-d57ed82ac6f8">

The runtimes per iteration are significantly greater for this instance than they are for the VRPTW instance (about 2x more, roughly in line with the increase in the number of unplanned clients).

## Conclusion

There is strong, positive connection between number of unplanned clients and the runtime of the subsequent local search. Having fewer unplanned clients appears to be better. Our current polar angle sort may not be up to the task, and we might want to investigate something better.

**Comment by N-Wouda** [comment]
Open question is whether this matters for actual performance/gaps to BKS, but I think it does: the CVRP instance I show here has an average gap of well over 1%, whereas the VRPTW instance is much better. If we can find a way to get less erratic behaviour in SREX for CVRP that instance may well converge better as a result.

**Comment by N-Wouda** [comment]
I've started some exploratory work with a Python-level heuristic over in the [`heuristic-srex`](https://github.com/PyVRP/PyVRP/tree/heuristic-srex) branch. WIP.

**Comment by N-Wouda** [comment]
On the branch linked above I have a heuristic that limits the number of unplanned clients fairly well, even when large numbers of routes are moved between parents. It is slow but that's largely because of Python. But I think we should investigate the importance of the number of routes that get exchanged, and what should go here:

https://github.com/PyVRP/PyVRP/blob/a147b704bb2229835d79cb3f2a67bc158b3942ea/pyvrp/crossover/selective_route_exchange.py#L74-L75

**Comment by leonlan** [comment]
I think SREX is a very important element in HGS, but I have put my bets on ILS. 
If someone wants to improve HGS further then I'd say that the following two cases are most interesting:
- Improve the heuristic for the subproblem (discussed above).
- How to make SREX deal more effectively with heterogeneous vehicles? I noticed in #617 that SREX does not correctly handle vehicle-client assignments. Even if the parents have no illegal vehicle-client assignment, the resulting offspring can have disallowed vehicle-client assignments.

@N-Wouda should we close this issue?

**Comment by N-Wouda** [comment]
I am not terribly interested in continuing my investigations into this, and would rather work instead on trying to get an ILS competitive. So, sure, we can close this.
