### ISSUE TITLE
Inform users that PyVRP only supports integral data

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#522]
We should explicitly state somewhere that PyVRP only supports integral data. I think this should be included in the quickstart example and somewhere else in the documentation. In both cases, we can advise users to scale their data to deal with floating-point numbers.

**Related**: should we make an exception for `Client.x` and `Client.y` and allow these to be floats? I assume most users will use long/lats as coords. Coordinates are not involved in cost/duration calculations anyway and `Route.centroid` internally is also represented using floats. 

--- 
Example: two points in Amsterdam (West and East)
- 52.3597897384259, 4.79539534000189 
- 52.35536406262091, 4.94998766369004

This needs a 1000x scaling factor to distinguish between the first two points. Could be even more when the points are closer to each other.

**Comment by N-Wouda** [comment]
Some ramblings:

> We should explicitly state somewhere that PyVRP only supports integral data. I think this should be included in the quickstart example and somewhere else in the documentation.

More explicit than the fact that all the types everywhere are `int`?

> **Related**: should we make an exception for `Client.x` and `Client.y` and allow these to be floats?

I'm leaning no because special-casing for this makes the (already somewhat hard) template stuff in `Measure.h` even harder. We could, but "everything's integral everywhere" is pretty easy to explain and for users to remember.

> Coordinates are not involved in cost/duration calculations anyway and `Route.centroid` internally is also represented using floats.

We need the centroid now for two very specific things: in SREX for the angle sort, and for the route neighbourhoods for the SWAP* operator. I think we can remove both uses in the near future, and replace them with something more robust. Then we could get rid of the centroid calculation altogether, which would move this stuff back to the users to compute if they want it (who can then decide themselves what to do).

**Comment by leonlan** [comment]
> More explicit than the fact that all the types everywhere are int?

Yea, I think we can make this more explicit because the fact that we only use or type hint ints is not obvious to beginner Python users. OR-Tools has a similar restriction because of constraint programming, and quite a number of [questions](https://www.google.com/search?client=firefox-b-d&q=or+tools+floating) have been asked about it.

> I'm leaning no because special-casing for this makes the (already somewhat hard) template stuff in Measure.h even harder. We could, but "everything's integral everywhere" is pretty easy to explain and for users to remember.

Sure.

> We need the centroid now for two very specific things: in SREX for the angle sort, and for the route neighbourhoods for the SWAP* operator. I think we can remove both uses in the near future, and replace them with something more robust. Then we could get rid of the centroid calculation altogether, which would move this stuff back to the users to compute if they want it (who can then decide themselves what to do).

I agree with this. Linking to #126 for context.

**Comment by leonlan** [comment]
So, to delve a bit deeper into the user side of things, I ran the following quickstart script and changed the input to be floats.

<details>
<summary>quickstart.py</summary>

```python
# fmt: off
COORDS = [
    (456, 320),  # location 0 - the depot
    (228, 0),    # location 1
    (912, 0),    # location 2
    (0, 80),     # location 3
    (114, 80),   # location 4
    (570, 160),  # location 5
    (798, 160),  # location 6
    (342, 240),  # location 7
    (684, 240),  # location 8
    (57, 400),  # location 9
    (912, 400),  # location 10
    (114, 480),  # location 11
    (228, 480),  # location 12
    (342, 560),  # location 13
    (684, 560),  # location 14
    (0, 640),    # location 15
    (798, 640),  # location 16
]
DEMANDS = [0, 1, 1, 2, 4, 2, 4, 8, 8, 1, 2, 1, 2, 4, 4, 8, 8]
# fmt: on

from pyvrp import Model

m = Model()
m.add_vehicle_type(4, capacity=15)
depot = m.add_depot(x=COORDS[0][0], y=COORDS[0][1])
clients = [
    m.add_client(x=COORDS[idx][0], y=COORDS[idx][1], delivery=DEMANDS[idx])
    for idx in range(1, len(COORDS))
]

locations = [depot, *clients]
for frm in locations:
    for to in locations:
        distance = abs(frm.x - to.x) + abs(frm.y - to.y)  # Manhattan
        m.add_edge(frm, to, distance=distance)

from pyvrp.stop import MaxRuntime

res = m.solve(stop=MaxRuntime(1))  # one second

```

</details>

 
When setting depot coordinates to floats, this just kills the program:

```
❯ poetry run python quickstart.py
libc++abi: terminating due to uncaught exception of type pybind11::error_already_set: TypeError: 'float' object cannot be interpreted as an integer
[1]    40022 abort      poetry run python quickstart.py
```

Setting client data to floats raises a more legible error,

```
TypeError: 'float' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/leonlan/Dropbox/PyVRP/quickstart.py", line 29, in <module>
    clients = [
              ^
  File "/Users/leonlan/Dropbox/PyVRP/quickstart.py", line 30, in <listcomp>
    m.add_client(x=COORDS[idx][0], y=COORDS[idx][1], delivery=DEMANDS[idx])
  File "/Users/leonlan/Dropbox/PyVRP/pyvrp/Model.py", line 137, in add_client
    client = Client(
             ^^^^^^^
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pyvrp._pyvrp.Client(x: int, y: int, delivery: int = 0, pickup: int = 0, service_duration: int = 0, tw_early: int = 0, tw_late: int = 9223372036854775807, release_time: int = 0, prize: int = 0, required: bool = True, name: str = '')

Invoked with: 1.798, 640, 8, 0, 0, 0, 9223372036854775807, 0, 0, True, ''
```

(I don't really understand why the messages for Depot and Client are different, but we should try to fix the Depot one.)


I think a simple message in the quickstart notebook is sufficient, something like this.

> Note: PyVRP only supports integer values. If you want to use floating point values like longitude and latitude, you must scale your data to integers to make them compatible.

**Comment by N-Wouda** [comment]
Yeah that makes sense. I don't really know why the error messages are different, but I'll have a look  soon!

**Comment by N-Wouda** [comment]
> * [ ]  I don't really understand why the messages for Depot and Client are different, but we should try to fix the Depot one.

What I think is happening is that the client error gets caught because it is inside a comprehension, and then re-raised with more Python details attached. That has nothing to do with the original error message, which is the same for both (one ends up terminated by the C++ runtime; the other - due to the comprehension? - by the Python runtime).

**Comment by N-Wouda** [comment]
Done all these things in #527!
