### ISSUE TITLE
Suboptimal solution for small PCTSP instance

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#539]
#### Is your feature request related to a problem? Please describe
PyVRP is unable to solve a small PCVRP instance optimally. The script below solves a PCVRP instance with eight clients and appropriately scaled prizes/distances. However, PyVRP gets stuck at the solution [8, 5, 4, 2, 1] with cost 4116, while the optimal solution is [8, 5] with cost 2875.

I tested this on PyVRP v0.7.0 and current main ([f6eadb8](https://github.com/PyVRP/PyVRP/commit/f6eadb8349b981eecb55bb9da7bdc5eaca802890)). See example script and output below.

<details>
<summary>Example </summary>

```python
import pyvrp
import pyvrp.stop


NUM_CLIENTS = 8

PRIZES = [454 for _ in range(NUM_CLIENTS)]
COORDS = [
    [844, 844],
    [1017, 855],
    [0, 1347],
    [1684, 833],
    [3438, 1009],
    [4078, 1015],
    [4288, 522],
    [3584, 1048],
]
DISTS = [
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 173, 983, 840, 2599, 3238, 3459, 2747],
    [0, 173, 0, 1130, 667, 2426, 3065, 3288, 2574],
    [0, 983, 1130, 0, 1761, 3455, 4092, 4367, 3597],
    [0, 840, 667, 1761, 0, 1763, 2401, 2623, 1912],
    [0, 2599, 2426, 3455, 1763, 0, 640, 980, 151],
    [0, 3238, 3065, 4092, 2401, 640, 0, 536, 495],
    [0, 3459, 3288, 4367, 2623, 980, 536, 0, 879],
    [0, 2747, 2574, 3597, 1912, 151, 495, 879, 0],
]


m = pyvrp.Model()

m.add_depot(x=10, y=10)
m.add_vehicle_type(1)

for idx in range(NUM_CLIENTS):
    m.add_client(
        x=COORDS[idx][0],
        y=COORDS[idx][1],
        prize=PRIZES[idx],
        required=False,
    )

for frm_idx, frm in enumerate(m.locations):
    for to_idx, to in enumerate(m.locations):
        m.add_edge(frm, to, distance=DISTS[frm_idx][to_idx])

result = m.solve(stop=pyvrp.stop.MaxRuntime(1))
cost_eval = pyvrp.CostEvaluator(1, 1, 1)


best = result.best
print(best, cost_eval.cost(best))

optimal = pyvrp.Solution(m.data(), [[8, 5]])
print(optimal, cost_eval.cost(optimal))
```

Running this script returns:
```
Solving an instance with:
    1 depot
    8 clients
    1 vehicle (1 vehicle type)

                  |       Feasible        |      Infeasible
    Iters    Time |   #      Avg     Best |   #      Avg     Best
H     500      0s |  44     7791     4116 |   0        -        -
     1000      1s |  52     7226     4116 |   0        -        -
     1500      1s |  60     6811     4116 |   0        -        -

Search terminated in 1.00s after 1540 iterations.
Best-found solution has cost 4116.

Route #1: 8 5 4 2 1 
 4116
Route #1: 8 5 
 2875
```

</details>

#### Describe the solution you'd like
PyVRP should solve this instance optimally.

#### Describe alternatives you have considered
- This is a TSP instance; ordered crossover is used since v0.7.0 so that's not a problem.
- Adding more of the same initial solutions does not work.
- I could fix this problem by adding one single-client solution, e.g., [1]. Any client works.

#### Additional context
The example was provided by Pedro.

**Comment by N-Wouda** [comment]
Might be a bug. Definitely something to investigate.

**Comment by N-Wouda** [comment]
I have some time right now. Let me investigate.

**Comment by N-Wouda** [comment]
I end up with a solution `Route #1: 1 2 4 5 8`, with the same cost 4116. Makes sense, the problem is not directed.

One issue is that removing any of clients 1, 2, or 4 in isolation isn't an improving move (the cost delta of such a removal is positive). Since that's the only way we can "lose" clients in a TSP setting, we never remove them from the solution. In a VRP setting, using SREX, we typically lose some clients along the way, resulting in a variety of incomplete solutions. But with OX for TSP, that never happens. Since our initial random solutions are all complete, only clients that are not improving on their own are removed in the local search, and we are left with too many clients because removing them individually does not get us to an optimal solution.

There are a few ways forward:
- Add more, non-complete solutions to the initial solution pool;
- Add removal operators that consider more than one client at a time;
- Somehow update OX to consider not reinserting all clients from both solutions?

**Comment by leonlan** [comment]
>    Add more, non-complete solutions to the initial solution pool;

I think revising our initial solution strategy is good, given the newly supported #514. For GVRP, we also add all clients to the initial solution, which seems unnecessary.

>    Add removal operators that consider more than one client at a time;

Maybe this could work but it may be easier to revise the initial solution strategy.

>    Somehow update OX to consider not reinserting all clients from both solutions?

Let's keep the implementation of OX as original as possible because it's so widely used.

**Comment by leonlan** [comment]
For the initial solution strategy I propose:
- If there are mutually exclusive groups: select 1 client randomly per group.
- For the remaining non-required clients, select randomly between $[1, k]$ clients, where $k$ is the number of non-required clients that are not part of a group.
- Proceed with the procedure as we have now.

**Comment by N-Wouda** [comment]
> When we have client-vehicle restrictions (#329) it may also be worthwhile to take this into account in the initial solution strategy, but that's for later.

If we get this via vehicle-dependent dist/dur matrices (I think we will) then it'll be difficult to bake this into the random solution - it's just a cost, there's no further information available. But let's see how important it actually is to take this into account first.

**Comment by N-Wouda** [comment]
Let's see if we can pick this up as part of 0.9.0, by modifying the initial solution pool a bit.
