### ISSUE TITLE
How to deal with triangle inequality?

### ISSUE THREAD

**Issue by wouterkool** [PyVRP/PyVRP#56]
Assuming the triangle inequality $d_{ij} <= d_{ik} + d_{kj} \ \forall i,j,k$ may allow for some optimizations, e.g.:
- assuming that removing one or more customers from a route will decrease cost, timewarp etc. this way we can avoid computing `TWS::merge` in some cases, e.g. if the current timewarp is 0.

The triangle inequality will hold for Euclidean cases (GH benchmarks) but in theory it can be violated for non-euclidean instances. Do we want to support 100% correctness of the local search operators (in that they never miss an improving move in the neighbourhood) or do we want to accept some edge cases will be skipped in favour of performance?

One idea could be a compiler switch ;).

**Comment by N-Wouda** [comment]
My 2¢: I don't think it's worth introducing a benchmark-specific flag just for this, butI would rather focus efforts on things that improve performance in the general case.

**Comment by N-Wouda** [comment]
(this seems pretty stale to me)
