### ISSUE TITLE
Persist Result or Statistics data to filesystem after a run

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#59]
The Euro/NeurIPS repository had a `Statistics::toCsv` method to persist Statistics data as a CSV file. That method has not (yet) been reimplemented. 

We do still have an `Individual::toFile` method that persists a solution, however. This too persists some sort of state to yet another file.

Can we streamline writing to/from files in some way? Perhaps to/from a JSON object, and then the whole Result object, not just the Individual or the Statistics?

**Comment by wouterkool** [comment]
Maybe we could do it somewhat like PyTorch:
* Have `get_state_dict`/`load_state_dict` methods that return a dictionary/load state from a dictionary
* Have `pyvrp.save(dict, filename)` and `pyvrp.load(filename)` to save to file, either use proprietary format (e.g. `pkl`) or let user specify format (e.g. `json`)
* We can implement this function on individual, population, but also on genetic algorithm itself so we could also use it for checkpointing the state of an algorithm to resume later (e.g. for use on spot compute instances)

**Comment by N-Wouda** [comment]
The biggest issue to persisting an Individual is that it takes a `PenaltyManager` instance, which we should really get rid of. @wouterkool your suggestion of passing the relevant penalties to `Individual::cost()` is probably what we should go for.

**Comment by N-Wouda** [comment]
>We do still have an `Individual::toFile` method that persists a solution, however. This too persists some sort of state to yet another file.

I have removed this in #58, and instead print that information when calling `str(individual)` from Python. So if one wants to write a individual to a file, one could (for now) do
```python
with open(file, 'w') as fh:
    fh.write(str(individual))
```

**Comment by N-Wouda** [comment]
Statistics has for some time now supported writing to a CSV, and reading a CSV back into a Statistics object. So that should be OK in terms of human-readable output.

Serialising a Result object is a bit harder, because of the underlying `Solution`. I think we should go towards pickling the whole thing, because [pybind has great support for that](https://pybind11.readthedocs.io/en/latest/advanced/classes.html#pickling-support). If we make `Solution` pickleable we should be done in terms of serialisation. The other objects in Result and Statistics should already be pickleable out of the box (but we should write tests that confirm this in `test_Result.py` and `test_Solution.py`).

**Comment by N-Wouda** [comment]
I'm assigning myself and will work on this tomorrow. Should be pretty easy to do.

When we have pickle support for these objects, we do not explicitly need to provide ways to load or save them: the [`pickle`](https://docs.python.org/3/library/pickle.html) module provides that out of the box. All we need to do is explain this somewhere.
