### ISSUE TITLE
Rename distance_matrix to (travel_)duration_matrix

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#60]
Hadn't really given this much thought, but everything's of course in time units, so we shouldn't talk about a "distance matrix" so much. We need to update a few places in the code to reflect this.

**Comment by N-Wouda** [comment]
>I haven’t seen this before in any of the existing VRPLIB instances though.

That makes sense to me. The typical VRPLIB instances are quite stylised, so I'd expect this kind of stuff not to be present. On our end, there's nothing stopping us from writing a ProblemData class that can accept two matrices (cost + time), and another 'shortcut' constructor that simply copies one into the other, when only one has been provided.

**Comment by wouterkool** [comment]
* I don't think there is a VRPLIB instance having both distance and time, and if it supports two matrices I don't think its unambiguous. Also note there is distance, time and (in theory) costs, which may be a combination of distance and time or even completely something else (general support of objectives is another topic anyway). You can replace distance by cost except if you want to support constraints like maximum route distance. Anyway, I don't think we should let our support depend on the VRPLIB format.
* For now we can either choose to just support duration, or do both, indeed by default being equal. However we should make sure having two matrices does not affect performance?
