### ISSUE TITLE
Use ragged arrays for mutually exclusive groups in GVRP instances 

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#626]
Mutually exclusive groups in GVRP instances are presented like this:

```
MUTUALLY_EXCLUSIVE_GROUP_SECTION
1	1
2	4
3	91
```

Here, each row corresponds to a location index and its corresponding group index. The choice for this format due to a limitation in VRPLIB as it could not parse ragged arrays. Now that VRPLIB 1.4.0 supports ragged arrays, we can change it back to the original format like this:

```
MUTUALLY_EXCLUSIVE_GROUP_SECTION
1 150 87 -1
2 107 -1
3 2 -1
4 160 -1
```

Here, the first index is the group index, followed by location indices that belong to this group. We should probably leave out the -1.

- [x] Update instances
- [x] Update read.py

**Comment by N-Wouda** [comment]
@leonlan is this something you want to pick up?

**Comment by leonlan** [comment]
Yup I'll do it today!
