### ISSUE TITLE
Enhancement Request: Support for Skill VRP with Precedence Constraints

### ISSUE THREAD

**Issue by JY00002** [PyVRP/PyVRP#648]
Body:
Hello,

Firstly, I would like to express my admiration for the project. It has been an invaluable resource in the field of vehicle routing problems, and the community has greatly benefited from the open-source nature of the work.

Moving forward, I believe there is an opportunity to further enhance the project's capabilities by introducing support for a Skill Vehicle Routing Problem [(Skill-VRP)](https://link.springer.com/chapter/10.1007/978-3-642-21527-8_40) model that differentiates vehicles not only by skill levels but also by skill types. This would allow for a more nuanced approach to fleet management in scenarios where a variety of service types are provided.

Additionally, incorporating precedence constraints into the model would be a significant advancement. For instance, in cases where a fleet of vehicles offers services A, B, and C, and there is a requirement for customers to receive these services in a sequential order before a vehicle can return, the ability to plan routes efficiently with this in mind would be highly beneficial. The objective would be to minimize the total travel cost while respecting the service sequence.

Here are the key requirements for this enhancement:

1.Recognition of different skill types for vehicles.
2.Implementation of precedence constraints for service order.
3.Optimization algorithms to ensure minimal travel costs.
The inclusion of these features would greatly expand the project's applicability to a broader range of logistics and service provision challenges.

Thank you for considering this enhancement request. I am eager to see how it could be implemented .

**Comment by leonlan** [comment]
Closing this issue because I think it is answered. Feel free to continue commenting on this issue if you still have related questions.
