### ISSUE TITLE
Wheels for Python 3.13

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#662]
#### Is your feature request related to a problem? Please describe

Python 3.13 was released a few weeks ago, but we do not yet have wheels for it. We should add them.

#### Describe the solution you'd like

Compile and distribute wheels for Py 3.13.

**Comment by leonlan** [comment]
If we drop 3.9, we can:
- replace `Optional[int]` by `int | None`
- replace `Union[int, list]` by `int | list`
- use match/case

Colab uses 3.10 so I'm OK with dropping support for 3.9.
