### ISSUE TITLE
several time window for depot and customer

### ISSUE THREAD

**Issue by HodaBinaei** [PyVRP/PyVRP#671]
#### Is your feature request related to a problem? Please describe
A clear and concise description of what the problem is. 
For example, start with "I'm always frustrated when [...]", and go from there.
Several customers have some time slots that need to be visited for example ([8:00-9:00], [14:00,15:00], [17:00-17:50]) for customer 1,....).
Also, I have some cars with some time slots which is available time for them (available time for car1:([8:00-14:00], [17:00-19:00]))
so they have the same location in these time slots, when I calculate the coordinates then I have an error

#### Describe the solution you'd like
I would like to optimize the number of covering each time slot and minimize the traveling time 

#### Describe alternatives you have considered
A clear and concise description of any alternative solutions or features you have considered.

#### Additional context
Add any other context about the feature request here.

**Comment by leonlan** [comment]
Hi @HodaBinaei, it's not really clear what your question is. It seems like you are trying to solve a [VRP with multiple time windows](https://pubsonline.informs.org/doi/10.1287/trsc.2021.1120), but you have to spend some more effort describing your problem before I can help you further.

**Comment by HodaBinaei** [comment]
Hi @leonlan 

Thank you so much for your reply. 
the problem is:

A care office manages n carers for m patients (where n<m), assigning carers to patient-requested time slots where carers also have some time slots available. Each week or day, patients submit requests for time slots, and the office needs to efficiently assign carers to minimize operational costs.

Key Requirements:
Patients
Consistency: Aim to assign the same carers to patients repeatedly for familiarity.
Multi-Carer Slots: Some time slots may need more than one carer.
Time Flexibility: Patients may allow a ±30-minute flexibility.

Carers
Two Carer Types:
Sr. Carers: Fixed 40-hour weekly shifts, to be prioritized in assignments, with required work over 9 of 14 days.
Local Carers: Variable availability and minimum hours, used once Sr. carers’ hours are scheduled.
Breaks:
15 minutes every 4.5 hours or 45 minutes after 6 hours.
Driving time counts toward working hours, but breaks do not.
Travel and First Shift: Initial travel is from the carer’s home to the patient, while subsequent travel is patient-to-patient.
This program will enable efficient weekly or daily scheduling, improving patient satisfaction through consistent assignments and optimizing carer shifts with break compliance and minimized travel time.
Thank you so much.

**Comment by leonlan** [comment]
You can check out the examples at https://pyvrp.org/examples/quick_tutorial.html to see how you can use PyVRP to solve your problem. Again, it’s not clear what your specific question is, so I’m going to close this issue.

**Comment by HodaBinaei** [comment]
Sorry for being unclear. 

 I read in https://pyvrp.org/examples/quick_tutorial.html , "Multi-depot VRP with time windows", but there is just one time window, how about more than one time window for each location?  (If some customers need several times delivery in a day in several time-windo) 
 I mean 
 # fmt: off
TIME_WINDOWS = [
    (0, 999),  # location 0 - a depot 
   [ (8, 19), (22,24)] # location 1 - a depot 
    [(9,10), (14, 15), (18,19)] # location 2
   [ (10,11),(16, 17), (20,21)],  # location 3
    (10, 13),  # location 4
.
.
.
]

**Comment by leonlan** [comment]
If they need multiple deliveries on a single day then you can simply create one client for each delivery moment.
