### ISSUE TITLE
Vehicle duration constraint violated

### ISSUE THREAD

**Issue by dirkcremers** [PyVRP/PyVRP#678]
**First of all, thank you for the hard work on this package—it's very well designed! Kudos to the entire team!**

#### Describe the bug

I implemented a Vehicle Routing Problem (VRP) with constraints on maximum vehicle duration and capacity. Based on these constraints, I expected the maximum duration limit for each vehicle to be respected. However, in my post-processing analysis, I observed that some trucks exceed the maximum duration limit by a small margin (5% above the maximum duration). Despite this, the solution indicates a feasible outcome.

#### Code sample

```python
m = Model()
m.add_vehicle_type(
    no_vehicles,
    max_duration=480,  # Maximum duration in minutes
    capacity=14,       # Vehicle capacity
)

# Define the depot and client locations
locations = [depot] + clients
for frm_idx, frm in enumerate(locations):
  for to_idx, to in enumerate(locations):
      distance = df_distance[frm_idx][to_idx]
      duration = df_time[frm_idx][to_idx]
      m.add_edge(frm, to, distance=distance, duration=duration)
```

<details>

Release version: PyVRP v0.9.1

</details>

#### Expected Output

I expected the model to respect the maximum duration constraint of 480 minutes for each vehicle. However, after running the model, I found that the returned solution does not fully comply with this constraint, even though it is marked as a feasible solution.

I compared this with a solution from OR-Tools using the same configuration, and although it resulted in a slightly higher objective, it respected the maximum duration constraint.

Is this behavior expected, or is there a way to enforce strict adherence to the maximum duration constraint? If you need further details, I’d be happy to provide them.

**Comment by N-Wouda** [comment]
Hi @dirkcremers, could you provide a _complete_ (but preferably small) example that I could run locally?

**Comment by dirkcremers** [comment]
Thank you for the quick response, @N-Wouda! I created a small example to reproduce the issue, and it seems to be working fine. I'll take another look tomorrow to see if there might be a minor issue in the larger dataset. I'll keep you updated!

**Comment by leonlan** [comment]
@dirkcremers Have you considered the possibility that the route start time could be non-zero? The route duration is defined as the difference between the end time and start time of the route, so it could be that your route ends later than 480 but starts later as well.

**Comment by dirkcremers** [comment]
I double-checked the larger dataset this morning, and it appears the issue is on my end. Small deviations are occurring due to the transformation from floating-point numbers to integers, which the model requires. Apologies for the confusion!

I have another question related to a specific constraint: Would it be possible to assign two time windows to a client, such as allowing delivery between 0-10 and 15-20? From reviewing the underlying classes, it appears that this option may not be supported, as the tw variable currently only accepts a single integer value. Implementing this feature could be challenging and may also impact the heuristic solution’s performance. So curious to hear your thoughts.

**Comment by N-Wouda** [comment]
> Small deviations are occurring due to the transformation from floating-point numbers to integers, which the model requires.

Yes! I believed this might have been the case, but I wanted to see an example to make sure. Great you figured it out on your own! For what it's worth: I often express time in seconds and distance in metres in my applications, and then convert the results back to whatever base unit makes most sense during post-processing.

> I have another question related to a specific constraint: Would it be possible to assign two time windows to a client, such as allowing delivery between 0-10 and 15-20? From reviewing the underlying classes, it appears that this option may not be supported, as the tw variable currently only accepts a single integer value. Implementing this feature could be challenging and may also impact the heuristic solution’s performance. So curious to hear your thoughts.

We support this (somewhat - I do not know how good the actual solutions are that it produces) via mutually exclusive client groups. We got a question about this recently (https://github.com/PyVRP/PyVRP/discussions/673) that also includes some example code.
