### ISSUE TITLE
Get the cost of a Solution without a Result: Solution.cost() method

### ISSUE THREAD

**Issue by selting** [PyVRP/PyVRP#714]
#### Is your feature request related to a problem? Please describe
I use the PyVrp interface for my custom workflow. E.g., I use the Client, Depot and in particular, the Solution() classes even for my own VRP solvers because this allows me to have a consistent interface.
Currently, to get the cost of a solution, I have to first create a Result that holds the solution in its .best attribute, and then call result.cost().
It would be nice to be able to get the cost of a single solution directly by calling solution.cost()

#### Describe the solution you'd like
Make Solution.cost() return the result of CostEvaluator(0, 0, 0).cost(solution).

#### Describe alternatives you have considered
- create a Result that holds the solution in .best
- call CostEvaluator().cost(solution) manually

#### Additional context
This would probably require the Solution class to have a CostEvaluator attribute. This might compromise flexibility, but currently the Result class also seems to use the default CostEvaluator(0, 0, 0): https://github.com/PyVRP/PyVRP/blob/0534f008cd263c995131f98a484f01cc8e19a52e/pyvrp/Result.py#L51

**Comment by N-Wouda** [comment]
Hi @selting,

> * call CostEvaluator().cost(solution) manually

What's the problem when using this alternative approach? I appreciate that `solution.cost()` reads slightly nicer, but I am hesitant to (re)introduce a dependency between the solution state and the cost evaluator for only that reason.
