### ISSUE TITLE
Overall Python structure

### ISSUE THREAD

**Issue by wouterkool** [PyVRP/PyVRP#73]
We should discuss the overall structure of the Python code, as well as how to deal with imports (absolute or relative) and what we make part of the public API (e.g. directly importable from `pyvrp`).

              @wouterkool agree. I don't really have a strong philosophy on these. In tests I typically prefer absolute imports, but in package code I use relative imports for siblings, and absolute imports (from `pyvrp`) for everything else. We should have a look at writing this down at some point. Would you be willing to open an issue for this?

_Originally posted by @N-Wouda in https://github.com/N-Wouda/pyvrp/issues/58#issuecomment-1420582556_

**Comment by N-Wouda** [comment]
I think the overall structure has largely crystalised over the past months. FWIW, I'm pretty happy with out current module/package division, so I don't think we have to change that too much anymore.

For the imports, I'll open a PR that moves everything over to absolute in regular files, and relative in the package-level `__init__.py`.

**Comment by N-Wouda** [comment]
I had a brief look around and that (relative in `__init__` to define the API; absolute in other cases) seems to be how more packages do it (numpy, statsmodels). So we're in good company.
