### ISSUE TITLE
Write "getting started" pages

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#78]
For this we can borrow structure quite a bit from the ALNS documentation: https://alns.readthedocs.io/en/latest/. If we are smart about this we can use parts of the doc texts for the paper.

**Comment by N-Wouda** [comment]
I've added many of these pages. Only "Intro to HGS for VRP" remains (here: https://pyvrp.readthedocs.io/en/latest/setup/introduction_to_hgs.html). @wouterkool would you be willing to write that page for the docs?

**Comment by N-Wouda** [comment]
I've added a short bit of text for the index page (which - embarrassingly - still said TODO). All that remains for now is to write the [introduction to HGS](https://pyvrp.readthedocs.io/en/latest/setup/introduction_to_hgs.html) page!

For some inspiration, perhaps the [same page for ALNS](https://alns.readthedocs.io/en/latest/setup/introduction_to_alns.html) might be useful.

**Comment by N-Wouda** [comment]
@leonlan do you have an update? This and #31 are the last two we still need to do for the stuff we promised in the paper.

**Comment by leonlan** [comment]
I'm working on this right now. I am also adding a page named "introduction to VRP".

**Comment by N-Wouda** [comment]
🎉
