### ISSUE TITLE
Generalise MoveTwoClientsReversed to (N, M) reverse exchange

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#94]
Which is more or less the same as (N, M)-exchange, but then flips the order of the N and M segments.

Maybe for the future.

**Comment by N-Wouda** [comment]
Not sure if this is useful. First check how much the current reverse exchange operator matters.

**Comment by N-Wouda** [comment]
I'm closing this because it'll never happen :-).

**Comment by leonlan** [comment]
> Not sure if this is useful. First check how much the current reverse exchange operator matters.

Do we event want to keep it at all? I recall from experiments that it doesn’t add anything to the LS in terms of performance. (Same thing for Exchange<n,m> with n > 1 or m > 1, but that is templated anyway.)

**Comment by N-Wouda** [comment]
> Do we event want to keep it at all?

Not principally opposed to removing it, but we'd need some benchmarks to confirm we can do without before we get rid of it.
