### ISSUE TITLE
Refactor Node and Route structures

### ISSUE THREAD

**Issue by N-Wouda** [PyVRP/PyVRP#96]
These structures are tied together quite closely, but that's not evident from how they are currently used. Further, these objects are clearly not in charge of their internal state: LS and the operators modify this repeatedly. 

Additionally, we do no really test these objects yet since they are mostly internal to the C++ implementation of LS. We should probably bind and test them in much the same way we did for `TimeWindowSegment`.

**Comment by N-Wouda** [comment]
To further develop this a bit, I'd like `Route::Node` to be a really simple class or struct that stores only the bare minimum like
```cpp
struct Node
{
    size_t client;
    size_t position;
    Route *route;
}
```
The time window, load, and distance statistics can all be moved over to `Route`. Similarly, inserting/removing nodes is something the `Route` should be in charge of. I think we can also get rid of the linked list model with `p()` and `n()`, using positions and indexing/slicing instead, perhaps using [`std::span`](https://en.cppreference.com/w/cpp/container/span) for efficiency.

Getting to that point will take significant refactoring, but should leave us with objects that are (a) in control of their internal state, and (b) easier to test because they can only be modified in very clear ways.

**Comment by wouterkool** [comment]
This may be related to #51 (proposal to use `end` index as exclusive).

**Comment by N-Wouda** [comment]
We will no longer need the `position` attribute once `Route` owns its nodes. That can trivially be computed as
```cpp
int Node::position()
{
    auto const &nodes = route->nodes;
    return std::distance(nodes.begin(), this);
}
```

**Comment by N-Wouda** [comment]
[from #320]

I think two/three more PRs after this:
- Make `Route` take ownership of the `Route::Node`s - no more pointers to memory owned by `LocalSearch`. The LS can maintain pointers to nodes instead, if needed. Remove the `idx` field; it can be calculated then (see #96 for details).
- Move the `Route::Node` TWS data to `Route`.
- Bind this to Python and add tests.

**Comment by N-Wouda** [comment]
> - [ ] [maybe?] Make `Route` take ownership of the `Route::Node`s - no more pointers to memory owned by `LocalSearch`. The LS can maintain pointers to nodes instead, if needed. Remove the `idx` field.

I might try this sometime later, but for now I don't think this is super important.
