### ISSUE TITLE
Reimplement SWAP* and 2-OPT from HGS-CVRP

### ISSUE THREAD

**Issue by leonlan** [PyVRP/PyVRP#99]
Two operators in our codebase are different than the ones originally implemented in HGS-CVRP:
- SWAP* here is approximated for TW compuitations, which is different from SWAP* in HGS-CVRP that works exactly for CVRP.
- There's also another 2-OPT move in HGS-CVRP (called one of move 7, 8 or 9, I don't know which one) includes segment reversals. 

We can reimplement these again to possibly improve performance on CVRP.
 
See https://github.com/vidalt/HGS-CVRP/blob/main/Program/LocalSearch.cpp.

**Comment by wouterkool** [comment]
Regarding 2-OPT, HGS-CVRP implements:
* Move 7: 2-OPT* within a single route, which reverses the route segment between node U and V
* Move 8: 2-OPT* accross two routes, which combines the starts of two routes (up to nodes U and V) into a new route, and the ends of the routes up to U and V, reversing the route segments up to node V and starting at U.
* Move 9: 2-OPT* accross two routes, which recombines the start of the route up to U with the end starting at V and vice versa, not reversing any route segments.

We currently implement Move 7 (`TwoOpt::applyWithinRoute`) and Move 9: (`TwoOpt::applyBetweenRoutes`) as Move 8 reverts around half of the route segments which is unlikely to yield improvements when considering time windows, for which the code was originally designed.

**Comment by N-Wouda** [comment]
> * SWAP* here is approximated for TW compuitations, which is different from SWAP* in HGS-CVRP that works exactly for CVRP.

@leonlan does PyVRP not revert to the original SWAP* when we compile the code for CVRP? Not sure.

> * There's also another 2-OPT move in HGS-CVRP (called one of move 7, 8 or 9, I don't know which one) includes segment reversals.

I'd rather implement 3-OPT as well. Iterated 3-OPT is pretty amazing, and we'd get that for free if we do this. We can perhaps generalise to a templated $k$-OPT operator.

**Comment by leonlan** [comment]
> Our current performance on CVRP is ~0.2% gap. I think that's plenty sufficient. Do we want to implement the HGS-CVRP operators described above to get even better gaps, or are we OK with what we have now? FWIW, I'm OK with never implementing the CVRP-specific operators described above.

I'm OK with the current situation too, so I'm closing this issue.
